Fix random failures of FoldersAsProjectsContributionTest #946
eclipse-platform/eclipse.platform.ui pull request #1000
Opened 2023-08-08 14:33 UTC by zelenyhleb

Using platform IFile::exists method instead of java.io.File::exists. Improved readability by removing some redundant private methods.

2023-08-08 15:03 UTC, zelenyhleb commented
I'm out of ideas for now :|

2023-08-09 05:59 UTC, BeckerWdf requested changes

2023-08-09 05:59 UTC, BeckerWdf commented on tests/org.eclipse.ui.tests.navigator/src/org/eclipse/ui/tests/navigator/resources/FoldersAsProjectsContributionTest.java
> +		assertTrue("Project description for inner1 does not exist",
shouldn't this be now something from inner1 iProject instead of a fixed string?

2023-08-11 11:07 UTC, BeckerWdf approved these changes

2023-08-11 11:08 UTC, merged