SoftLimit on viewers: hide ExpandableNode
eclipse-platform/eclipse.platform.ui pull request #1061
Opened 2023-08-23 14:10 UTC by mickaelistria

* Make that selection never contains ExpandableNode, since it's not part of model
* Selecting a not-yet-expanded node does nothing, similarly to how filtered elements are not selectable
* Make that only the TreeItem is accepted to check whether it's the expansion placeholder or not, to clarify it's not a model element we're chasing here.

2023-08-23 14:22 UTC, iloveeclipse commented
Please checkout jdt.ui project, see compiler errors and try to use SDK with this patch. It will not work. Code in classes below doesn't have `Item`, it only has model objects. So `org.eclipse.jface.viewers.ColumnViewer.isExpandableNode(Item)` API can't be used there.
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/javaeditor/JavaOutlinePage.java
- org.eclipse.jdt.ui/ui/org/eclipse/jdt/internal/ui/packageview/PackageExplorerPart.java
I haven't checked the rest of the patch, since that must be fixed first.

2023-08-23 14:30 UTC, iloveeclipse commented on bundles/org.eclipse.jface/src/org/eclipse/jface/viewers/AbstractTreeViewer.java
> +		// invisible items (part of expandable node, or filtered) are ignored
This breaks "link with selection" in the sense, that before this change, we selected the node contained "hidden element", so user could directly click on it to expand & eventually see the file. Now no selection updated at all.

2023-08-23 14:31 UTC, iloveeclipse requested changes
This change breaks JDT support and makes "link with editor" even worse as before.

2023-08-23 14:42 UTC, mickaelistria commented
`getSelection` and `link with selection` is still broken in the sense that the selected element in the editor area is still not selected (but the expandable node is). It's better to return nothing and break "link with selection" that to break "getSelection" so it returns virtual/internal/non-model objects. There are possible alternatives such as expanding the node until the target element is visible which would be much more correct, or if the expansion is too heavy because there are too many elements to show, maybe just expand the range of the selected element and show 1 expansion placeholder above and another below the newly expanded block.
But IMO, the current state of `getSelection` is deeply bogus compared to the legacy behavior which is as important as a contract: only selected model elements should be returned. I would rather see "link with selection" not support for expandable trees in next release than introducing such a critical change in `Viewer.getSelection()`.

I will look at JDT consumers soon.

2023-08-23 15:26 UTC, mickaelistria commented
I see the JDT consumers can most likely be removed as they do delegate to `hasFilteredChildren(parent)` or `super.isExpandable(parent)` for which the JFace TreeViewer implementation is supposed to return the right value (`false`) for the expandable node anyway.

2023-08-23 15:47 UTC, iloveeclipse commented
> I see the JDT consumers can most likely be removed

If you have a solution, please create a PR. Without changes the JDT UI simply doesn't work properly because on every click on the "special node" they create an extra tree level and add the children there and not as expected at the same level.

2023-08-23 16:58 UTC, iloveeclipse commented
> It's better to return nothing and break "link with selection" that to break "getSelection" so it returns virtual/internal/non-model objects.

I disagree, I do see a value in selecting the closest element to the hidden one and I see no issue with returning "special" node in selection.

> There are possible alternatives such as expanding the node until the target element is visible which would be much more correct

Which turns the entire idea ad absurdum, because it is exactly the use case that hangs UI.

> just expand the range of the selected element and show 1 expansion placeholder above and another below the newly expanded block.

If you have improvements, please provide PR's. But as long as this feature is not impemented, one should not break existing code that, if not perfekt, provides a better user experience as before.


> only selected model elements should be returned.

What is the problem with that? Where the Viewer.getSelection() says anything about concrete selection **content**? Can you point me to this?

> I would rather see "link with selection" not support for expandable trees in next release than introducing such a critical change in Viewer.getSelection().

Why is this critical? I do not see a problem you are trying to fix. Viewers that want to use new code need to be manually changed and if needed adopted, no viewer is automatically forced to use new functionality.

2023-08-23 23:28 UTC, mickaelistria commented
> I disagree, I do see a value in selecting the closest element to the hidden one and I see no issue with returning "special" node in selection.

"Link with selection" can maybe be improved to better support that case and select the placeholder element in case the element is not visible yet, that wouldn't be too bad. It's more `getSelection()` which can now return incorrect values.

> If you have improvements, please provide PR's. But as long as this feature is not impemented, one should not break existing code that, if not perfekt, provides a better user experience as before.

My concern is that we're near a release and we're about to release a change that does break important stable 20-years-old invariant (getSelection only return items that are from the model, returned by ContentProvider). Sure, the breakage is now opt-in, but what if we change the viewers default to incremental and some consumers have plugged in selection listeners that have worked forever and will now have to deal with this ExpandableNode in selection? The answer has already been found in Platform issues: some ClassCastException and other errors will pop-up; same errors will show-up in 3rd-party consumers of such viewers. Those errors will cause a worse user experience than before.

> What is the problem with that? Where the Viewer.getSelection() says anything about concrete selection content? Can you point me to this?

I think I remember you usually advocate that a stable behavior of some API is as important,or even more, than the contract of the API. This is an instance of this stability rule.

> Viewers that want to use new code need to be manually changed and if needed adopted, no viewer is automatically forced to use new functionality.

Imagine the viewer is changed, but is exposed and opened to 3rd-party extension to add listeners (example: the CNF navigator allows to plug many listeners to the Project Explorer). Those "legacy" listeners can then fail because the viewer can suddenly return unexpected selections, causing consumers to fail.


Again, I'm not trying to ditch the whole change, as I fully agree it does provide a better UX, it's just that the current API opens a room for bugs to happen in stable code, and I don't think it's a good thing to let it happen in a release.

If I manage to change `link with selection` to select the "Show more..." node in case the element is not available yet, would it be OK for you to apply this patch?

2023-08-24 04:59 UTC, iloveeclipse commented
> if we change the viewers default to incremental

We will not do that, the change breaks behavior and so can't be made default

> and some consumers have plugged in selection listeners that have worked forever and will now have to deal with this ExpandableNode in selection?

This was addressed already via https://github.com/eclipse-platform/eclipse.platform.ui/pull/1035q

> I think I remember you usually advocate that a stable behavior of some API is as important,or even more, than the contract of the API. This is an instance of this stability rule

Because usually new API isn't optional. Here no one client is broken without explicitly accepting that new invariant and consequences.

> just that the current API opens a room for bugs to happen in stable code

First of all, this might happen with any code change. Second, by default new behavior is disabled anyway. And if someone enables it and finds new issue, we would be happy to fix it (as with any other code change).

> If I manage to change ... 

If the user visible functionality remains, also for JDT UI, wh, not? 

But see above,  I'm pretty confident that stability shouldn't be affected and all new API is marked as experimental anyway. So if there will be a major refactoring later we should be fine changing this experimental API. Just consider this as a Java "preview" feature that might change. Everyone is warned - if you turn it on, you might need to adopt your code in the future. But this "preview" is the good way to find better solution and move forward. So why shouldn't we just do same here?

2023-08-24 07:03 UTC, mickaelistria commented
> This was addressed already via https://github.com/eclipse-platform/eclipse.platform.ui/pull/1035

Yes, but the unit test that are changed with this commit do highlight that it's still possible to get the ExpandableNode returned by JFace's `getSelection()`. I see my proposal here is a continuation of #1035

> Here no one client is broken without explicitly accepting that new invariant and consequences.
> ...
> But see above, I'm pretty confident that stability shouldn't be affected


That's unfortunately not entirely true, and the various "fixes" like the ones that were implemented in JDT's and other viewers are demonstrating the risk associated with that change for established viewers.
I've explained it in my previous message, but let me repeat it: some APIs (for example CommonNavigator) do expose a viewer instance to clients, including 3rd-party clients. If this client moves to "incremental display" because it's best for it, they would hope and even expect that clients are not broken by usage of this new flag, and may just enable incremental displayt because it's nice and easy to do so; and miss to think about the issue that consumers need to consider the ExpandableNode in the selection, and actually make those 3rd party consumers prone to ClassCastExceptions and so on.
So direct clients of the new API do it on their own risk, but when they start exposing the viewer, it's the clients of this clients that can crash the viewer because of the change in the invariant.

> And if someone enables it and finds new issue, we would be happy to fix it (as with any other code change).

This change does intend to fix the issue before someone finds it in a release ;)

> all new API is marked as experimental anyway. 

Right, but we should still try to make it as robust and stable as possible before releasing it.

> So if there will be a major refactoring later we should be fine changing this experimental API. Just consider this as a Java "preview" feature that might change. Everyone is warned - if you turn it on, you might need to adopt your code in the future. 

I've seen "experimental" APIs that got adopted too quickly by too many people so they got practically set stone after 1st release, and providers were unable to do the fix they had planned for the future. For Java they have a strict policy, enabling preview features is a burden that makes it very clear it can change. In Eclipse Platform, people may bind to experimental APIs without even noticing it, it's too easy to over-use an API, the "preview" approach of Platform is to weak to be reliable.
Hence why I want to push for highest quality ASAP, before the release.

I will investigate the "Link with editor" thing today.

2023-08-24 09:32 UTC, mickaelistria commented
So it seems like "Link with editor" doesn't work anyway as per https://github.com/eclipse-platform/eclipse.platform.ui/issues/1014 ?

2023-08-24 09:44 UTC, iloveeclipse commented
> So it seems like "Link with editor" doesn't work anyway as per #1014 ?

It works partly - it selects the node that "hides" expected element. So user sees what need to be expanded.

2023-08-24 09:48 UTC, mickaelistria commented
The reason why tweaks are needed in JDT seems to be another isuse with implementation in JFace: `getRawChildren()` for the ExpandableNode should *not* return children as the invariant in JFace is that the raw children are actual children, that are to be displayed as children.
Here, the API has been bent to serve a different purpose and it leads it to returning incorrect values that require adaptation in downstream consumers.

2023-08-24 11:22 UTC, mickaelistria commented
Although I would like to spend more time on this topic, I have some other priorities and am pessimistic about the possibility of improving this code substantially before the release. I'm giving up.

2023-08-24 15:43 UTC, raghucssit commented
@mickaelistria I will checkout this and fix what's remaining.

2023-11-05 07:27 UTC, akurtakov commented
Is this one still needed?

2023-11-05 07:58 UTC, iloveeclipse commented
> Is this one still needed?

It is obsoleted meanwhile. All points are fixed by @raghucssit in other PR's .

2023-11-05 07:58 UTC, closed without merging