Prototype: Handle tab icons and text for view area
eclipse-platform/eclipse.platform.ui pull request #1071
Opened 2023-08-29 09:04 UTC by praveen-skp

Issue: #735 

Currently, the UI/UX for Eclipse views does not scale properly when a perspective contains a lot of views. The current solution for scaling views in Eclipse is to provide lots of different perspectives and use them to group the views. If only a limited number of views are visible it means that the whole title of each view is visible and the usability is good but if the number views increase significantly then the following issues occur:

1) The tab titles get so small that only the view icons are visible. This means users have to learn all icons which is not ideal.
2) The overall look&feel of the IDE feels cluttered.
3) Lots of view icons draw attention away from the editor area. However, when playing the role as a classic IDE for a programming language the editor area should be most prominent.

Changes:
- As all three points are based on personal preferences, new eclipse preferences has been added for handling Tab icons and titles in View areas by providing two options 
a. Always show full titles 
b. Hide icons
<img width="1123" alt="Tab Icons and text preferences" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/18184080/9c260e16-50e9-431e-9480-65b2adab6a9e">

- Corresponding change to CTabRendering to handle these preferences and render the image and text for tabs in view areas accordingly
    - As a pre-requisite, added property "showSelectedImage" to CTabFolder : [Pull request](https://github.com/eclipse-platform/eclipse.platform.swt/pull/785)  

- Added two CSS properties handler
  - CSSPropertyTabTextMinimumCharactersSWTHandler: An swt property to set the minimum characters for CTabFolder
  - CSSPropertySelectedImageVisibleSWTHandler: An swt property to set if the selected tab's image should be visible or not

This a prototype and would like to get feedback

2023-08-29 14:13 UTC, albertmink commented
@praveen-skp can you provide a screenshot from the whole IDE, not only a view area (with hidden icons)? Such an example helps to explain the addressed change in _overall look&feel_

2023-08-30 07:45 UTC, BeckerWdf requested changes

2023-08-30 07:45 UTC, BeckerWdf commented on bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/custom/CSSPropertySelectedImageVisibleSWTHandler.java
> + * Copyright (c) 2009, 2016 IBM Corporation and others.
Adapt copyright header to 2023 and "SAP SE..."

2023-08-30 07:45 UTC, BeckerWdf commented on bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/custom/CSSPropertyTabTextMinimumCharactersSWTHandler.java
> +package org.eclipse.e4.ui.css.swt.properties.custom;
add copyright header

2023-08-30 07:45 UTC, BeckerWdf commented on bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/CTabRendering.java
> +	public static final String HIDE_ICONS = "HIDE_ICONS"; //$NON-NLS-1$
I would say "HIDE_ICONS_FOR_VIEW_TABS" better describes this.

2023-08-30 07:45 UTC, BeckerWdf commented on bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/CTabRendering.java
> +	public static final String SHOW_FULL_TEXT = "SHOW_FULL_TEXT"; //$NON-NLS-1$
"SHOW_FULL_TEXT_FOR_VIEW_TABS"

2023-08-30 07:45 UTC, BeckerWdf commented on bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/CTabRendering.java
> +		showFullText();
should be "showFullTextPreferenceChanged"

2023-08-30 07:45 UTC, BeckerWdf commented on bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/CTabRendering.java
> +		hideIcons();
should be "hideIconsPreferenceChanged"

2023-08-30 07:45 UTC, BeckerWdf commented on bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/CTabRendering.java
> +		} else {
else return can be omitted

2023-08-30 07:45 UTC, BeckerWdf commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/dialogs/ViewsPreferencePage.java
> +				if (state == false)
Formatting seems not to be according to the standards. Didn't you format it? Shouldn't it be 
if (!state) {
...

2023-08-31 04:21 UTC, praveen-skp commented
Screenshots for the whole IDE:
![Default](https://github.com/eclipse-platform/eclipse.platform.ui/assets/18184080/fc54a43a-b801-4c89-b20b-7467b2ec4e4f)
![Show full title](https://github.com/eclipse-platform/eclipse.platform.ui/assets/18184080/0969cb6f-3b70-438b-87a5-2c6fcd81fd1d)
![Show full title and hide icons](https://github.com/eclipse-platform/eclipse.platform.ui/assets/18184080/b212838b-a851-4507-896c-313328a190d1)

2023-09-13 14:39 UTC, iloveeclipse commented
Few things:
- if no icons shown for views, it would be nice to show **active** view with an icon
- Instead of hiding (small) icons and showing only (long) view titles, why not add an option to show no view titles. In this case, views will be shown by icons and only active one will have icon and title. **That** will save place and clearly set focus on what is active in each view stack.

2023-09-26 08:35 UTC, shubhamWaghmare-sap commented
@iloveeclipse 
> Few things:
> 
> * if no icons shown for views, it would be nice to show **active** view with an icon

This is already technically possible using the SWT API. We can consider incorporating this as a future update if required.

On a side note, we also observed that showing the icon (only) for **active** view could potentially increase screen flickering, as the text for the tabs would be moved each time a tab is switched. Thus the impact on user experience should be evaluated before proceeding.

> * Instead of hiding (small) icons and showing only (long) view titles, why not add an option to show no view titles. In this case, views will be shown by icons and only active one will have icon and title. **That** will save place and clearly set focus on what is active in each view stack.

Showing only icons is also technically possible and here is what it would look like:

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/57699330/07dd65c9-3c24-4550-bd01-1f1f81c7919a)

We had contemplated this option and consulted with UX experts who indicated the following potential issues related to accessibility:

- It would be difficult for users to identify a tab just by the icon.
- Users would need to learn/remember the icons for different views, which is not ideal.
- Figuring out if a view is already open or not would not be a quick task.
- Precise mouse movements would be needed to hit the required tab.

Moreover, the intention behind the change was not on saving space but to keep the focus only on editor area which is the _main actor_ in IDE. Thus the icons for all tabs from the view stack (_supporting actors_) are to be hidden, which might draw attention away from the editor area otherwise. 
Also the idea is to align the look & feel with other IDEs out there like VS code, where tabs in view stack always show full texts but no icons, which gives a cleaner look.

2023-09-26 08:49 UTC, BeckerWdf commented
Regarding "only show icons": It looks much more cluttered compared to the current state (Icon and Text). I have the feeling this is a move into the wrong direction.

2023-09-26 12:18 UTC, humphreygao commented
I think it is a good idea, you can provide this 2 options(show full titles and hide icons) and let users to decide. And it would be good to always show editor tabs' full name especially when you open  many editors.

2023-09-26 12:59 UTC, HeikoKlare reviewed
Thanks for the proposal. I really like it.

I have some minor code style comments and one general remark:
I am wondering whether it may be useful to allow the configuration for each part stack (not necessarily as part of this PR but as a future extension). You could then define the visualization that fits most for one specific stack of views. E.g., you may have one stack of views that you usually distinguish by their (full) names, so that you want to hide the icons and always show the full texts, and you may have a (horizontally) small stack of views of which you know well their icons, so that only showing the icons may be perfect for that stack (this would require to have the option of only showing icons as proposed in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1071#issuecomment-1717766464). This would relieve you from deciding about the visualization of tab items for the whole workbench. As a concrete example, in a "usual" perspective setup such as the Java perspective, displaying the full names of the tabs may be useful for the views in the stack at the bottom of the workbench window, while it may not be desired for the stack at the right side of the workbench window, as the names of one or two views can easily require all the available space for the tabs.
As an RCP application provider, you could even provide perspectives that are predefined accordingly. The preferences could then be used to define the initial behavior of newly created stacks.

2023-09-26 12:59 UTC, HeikoKlare commented on bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/custom/CSSPropertySelectedImageVisibleSWTHandler.java
> +			CTabFolder folder = (CTabFolder) control;
```suggestion
		if (control instanceof CTabFolder folder) {
```

2023-09-26 12:59 UTC, HeikoKlare commented on bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/custom/CSSPropertySelectedImageVisibleSWTHandler.java
> +			CTabFolder folder = (CTabFolder) control;
```suggestion
		if (control instanceof CTabFolder folder) {
```

2023-09-26 12:59 UTC, HeikoKlare commented on bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/custom/CSSPropertySelectedImageVisibleSWTHandler.java
> +		boolean isSelectedImage = (Boolean) engine.convert(value, Boolean.class, null);
I do not understand the name of the variable. Shouldn't it be something like `isImageVisibleForSelectedTab` or the like?

2023-09-26 12:59 UTC, HeikoKlare commented on bundles/org.eclipse.e4.ui.css.swt/src/org/eclipse/e4/ui/css/swt/properties/custom/CSSPropertyTabTextMinimumCharactersSWTHandler.java
> +			CTabFolder folder = (CTabFolder) control;
```suggestion
		if (control instanceof CTabFolder folder) {
```

2023-09-26 12:59 UTC, HeikoKlare commented on bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/CTabRendering.java
> +		return false;
```suggestion
		return element != null && element.getTags().contains(EditorTag);
```

2023-09-26 12:59 UTC, HeikoKlare commented on bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/CTabRendering.java
> +				Optional<Integer> max = Arrays.stream(parent.getItems()).map(CTabItem::getText).map(String::length)
Please rename the variable to something self-explaining like `lengthOfLongestItemText`

2023-09-26 12:59 UTC, HeikoKlare commented on bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/CTabRendering.java
> +				parent.setMinimumCharacters(max.orElseGet(() -> 9999));
Please assign this magic value to an explaining variable.

2023-09-26 12:59 UTC, BeckerWdf commented
> I think it is a good idea, you can provide this 2 options(show full titles and hide icons) and let users to decide. And it would be good to always show editor tabs' full name especially when you open many editors.

I would try to keep the number of configurations options as small as possible. Let's start with the current implementation of this PR. Let's see that what kind of feedback we get. We can add more configuration options later on. But pls. let's start simple.

2023-09-26 13:41 UTC, HeikoKlare commented
One further thing I forgot to mention: when removing the icons, it becomes really hard to see where one tab item ends and the next begins, as there are no borders between them. With the icons enabled, you directly see where the items starts. So maybe there should be some kind of small separator to see where a new tab item starts?

2023-09-26 14:44 UTC, BeckerWdf commented
> One further thing I forgot to mention: when removing the icons, it becomes really hard to see where one tab item ends and the next begins, as there are no borders between them. With the icons enabled, you directly see where the items starts. So maybe there should be some kind of small separator to see where a new tab item starts?

You are right. But is it necessary to see where "inactive" view tabs start and end exactly. If you want to bring it to the top you simple click on the text. Pls. look how VsCode does it - I also don't see separators there...

2023-09-26 14:57 UTC, HeikoKlare commented
> You are right. But is it necessary to see where "inactive" view tabs start and end exactly. If you want to bring it to the top you simple click on the text. Pls. look how VsCode does it - I also don't see separators there...

That's true. My concerns are not with respect to where the tab starts and ends exactly but with respect to identifying the text that belongs together, i.e., to a single tab, at all. The difference I see in comparison to VS Code is the size of the space between the texts. Maybe we could increase the padding to have a bigger difference between the size of a whitespace and the size of the space between tabs, so to make it easier to find the individual tabs?

For example, in the following tab folder, I find it quite hard to see where tabs start and end. It takes some time (or knowledge) to identify whether there are tabs "CSS" and "Scratch Pad" or whether it is a single "CSS Scratch Pad". Either I know that, I have to take a deep look for quite some time to distinguish the space between tabs and the whitespace between words, or I have to hover with the mouse to see the highlighting.

![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/cbbee839-e667-4eb1-a131-119d4c83ccd4)

In VS Code, I find it fairly easy to identify the individual tabs.
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/3aab576c-e364-4dd4-a9df-a7583873d929)

2023-09-27 06:17 UTC, BeckerWdf commented
> Maybe we could increase the padding to have a bigger difference between the size of a whitespace and the size of the space between tabs, so to make it easier to find the individual tabs?

Good idea.

2023-10-18 07:48 UTC, shubhamWaghmare-sap commented
> Maybe we could increase the padding to have a bigger difference between the size of a whitespace and the size of the space between tabs, so to make it easier to find the individual tabs?

Earlier the padding was only added to the selected tab. 
Now the padding is uniformly added across all tabs (selected and unselected) where tab icon would not be visible.
This is how it looks now and the change is done in https://github.com/eclipse-platform/eclipse.platform.swt/pull/785
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/57699330/6097bfc9-3a22-49d3-9351-f9669d739816)

For example, notice the significant space between _Type Hierarchy_ tab and _CSS Scratch Pad_ tab.

2023-11-28 16:43 UTC, HeikoKlare reviewed
With some further adaptations of the required SWT change https://github.com/eclipse-platform/eclipse.platform.swt/pull/785, this looks good to me.

I would be in favor of even larger paddings when no icons are shown, as also mentioned in the SWT PR (https://github.com/eclipse-platform/eclipse.platform.swt/pull/785#pullrequestreview-1753347506), which could look like this:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/66f85d61-4488-44de-90d0-d7da72e95a8c)
But that's a matter of personal preference.

2023-12-13 08:37 UTC, BeckerWdf approved these changes

2024-01-10 08:36 UTC, merged

2024-01-11 19:04 UTC, HeikoKlare commented
@shubhamWaghmare-sap Was it intended that the minimum number of characters shown for tabs now is 1 in case "always show full titles" is not enabled? That way it seems to become impossible to navigate between source code files 😇 
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/35e2b8a2-e4ea-407a-87d7-5dbc058480ef)

2024-01-12 09:56 UTC, thomasritter commented
Just tested the iBuild. In general it looks much cleaner. We should think about making the option "Always show full titles" the default, in the future. When the icons are visible everything looks great. Once I switch off the icons the tab title spacing is not ideal, in my opinion. When I look at the titles it feels like they are not bound to the beginning of the tab. They are leaning to the right. The reason for this is that the titles are not aligned in the center. I would recommend we align them. See screenshot:

<img width="303" alt="alignment_tab_titles_no_icons" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/41768/31138ab0-13bd-4196-9f9a-7c786951fec8">

2024-01-12 12:24 UTC, shubhamWaghmare-sap commented
> @shubhamWaghmare-sap Was it intended that the minimum number of characters shown for tabs now is 1 in case "always show full titles" is not enabled? That way it seems to become impossible to navigate between source code files 😇 ![image](https://private-user-images.githubusercontent.com/755472/296023013-35e2b8a2-e4ea-407a-87d7-5dbc058480ef.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDUwNTc4MzksIm5iZiI6MTcwNTA1NzUzOSwicGF0aCI6Ii83NTU0NzIvMjk2MDIzMDEzLTM1ZTJiOGEyLWU0ZWEtNDA3YS04N2Q3LTVkYmMwNTg0ODBlZi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMlQxMTA1MzlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hYThiYzlhYzJjNWUwNTNiOGQzZDY5Mzg4NDgwMWQxMTdiOGI3OTBjZTdjZWYyNTViNjNiMjIwYjZiMDc4OTZhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.TXh1nQtSNchYcPZP74992D0_NsCidWmXqBVY8wihGP0)

@HeikoKlare It seems that before this change, the minimum number of characters for tabs _"in view areas"_ was always 1. Also the newly added preferences do not affect the _"editor area"_.
The below screenshot corresponds to a commit before this change, where, we have a chevron in _"editor area"_ and only 1 character visible in _"view area"_. (same is the case when "always show full titles" is not enabled )

<img width="417" alt="image" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/57699330/1c637e7a-1d8a-46a8-9d77-7716c89c0624">

So,
1. Do you observe this issue in the _Editor area_ or in _View area_?
2. If you observe it in _View area_, is it expected to have a higher number for default minimum characters and have chevron instead ?
3. Is there a reason to suspect it to be a regression?

2024-01-12 14:13 UTC, HeikoKlare commented
Maybe I erroneously related the changed behavior to this PR. For me, the behavior changed in the _editor area_. This is how it looks like:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/1d985889-7550-4709-b25c-8655913b200b)

Behavior for the view area is fine for me, as it has been like this before, and you can usually also distinguish views by icons (in comparison to files in the editor area, where the single first letter does not help).

The changed behavior for the editor area (assuming that it is related to this PR) actually is a regression for me, because for me it is now ususable without "always show full titles" activated.

> Once I switch off the icons the tab title spacing is not ideal when the tab is in focus, in my opinion. When I look at the titles it feels like they are not bound to the beginning of the tab. They are leaning to the right. The reason for this is that the titles are not aligned in the center.

The SWT implementation for tab folders with disabled icons centers the text (like, e.g., VS code does). @thomasritter What do you mean by "leaning to the right"? The text actually should be centered. And making it left aligned will look strange, as then you have a huge space to the right as a separator to the next tab.

2024-01-12 15:26 UTC, thomasritter commented
@HeikoKlare If the tab is selected the area in which the text should be aligned runs from the left edge to the right X. See this screenshot. I added the black box. You can see that the text is not centered. It is too much to the right.

<img width="303" alt="alignment_tab_titles_no_icons" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/41768/9b64d284-150e-4a25-8aae-8fc57053d860">

2024-01-12 15:29 UTC, HeikoKlare commented
Thanks for clarification! I got it. The problem is that centering is performed w.r.t. the "text area", but the tab also has a padding on its own. We have to fix that in SWT.

2024-01-12 15:32 UTC, thomasritter commented
Ok, here a fake screenshot in which I fixed it manually and centered the text. This is how I would expect it to look like.

<img width="467" alt="alignment_tab_titles_centered" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/41768/8069a830-9670-47e6-9366-c7aefed124d4">

2024-01-12 15:40 UTC, HeikoKlare commented
Seeing the fake screnshot: do you really think that it looks better that way? It seems like my eyes expect the text to be centered "within the padding" of the tab, like in the current behavior. So the current behavior actually looks more "natural" to me than the proposed one.

2024-01-15 15:30 UTC, thomasritter commented
@HeikoKlare In order to get away from "feeling" and more towards empirical data I looked at the most widely used tab design and measured how they position the content (text + icon). Have a look at this diagram:

<img width="852" alt="image" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/41768/b9bb4d78-0675-4a6d-96e8-ae7db278bc30">

As you can see, almost all tab titles are leaning slightly to the left side of the tab. Only Intellij uses a centered design. As most humans read from left to right this makes a lot of sense to me. The content needs to feel anchored to the left side. This is not the case with the current design. My proposal would be to follow the padding of the Eclipse tab with icon or at least do not have more padding in the front than after the (x) button.

2024-01-17 15:45 UTC, HeikoKlare commented
Thanks for collecting that data, @thomasritter!

You compare the iconless tab design with other applications using icons in tabs. The reason why left alignment and small paddings work when using icons is that the icons work as a separator between individual tabs, which allows you to easily find the start/end of a tab.

When using an iconless design, you need to apply larger paddings to be able to distinguish tab start/end from whitespaces between words in a single tab (see my [previous comment](https://github.com/eclipse-platform/eclipse.platform.ui/pull/1071#issuecomment-1735717715)). From my point of view, using paddings as separators only works with centered text. Left-aligning the tab text looks really weird:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/11b1e5ff-a634-404b-8668-ba81a1f9746f)

To support this with some empirical data: VS code does it the same way (in the screenshot, the "Terminal" tab is moved between the "Output" and "Debug Console" tabs to show where VS code puts the border):
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/755472/44f9e01f-54a1-4695-be63-578de4b52355)