Show ZWSP (zero with space) as code mining
eclipse-platform/eclipse.platform.ui pull request #1437
Opened 2023-12-19 15:41 UTC by marcushoepfner

Issue: https://github.com/eclipse-platform/eclipse.platform.ui/issues/1002

For more information refer to https://www.compart.com/en/unicode/U+200B To get a ZWSP refer to https://zerowidthspace.me/

2023-12-19 15:58 UTC, mickaelistria commented on bundles/org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/internal/texteditor/codemining/ZeroWidthSpaceLineContentCodeMining.java
> +package org.eclipse.ui.internal.texteditor.codemining;
Missing co[yright header

2023-12-20 07:34 UTC, BeckerWdf commented
I did a quick manual test on macOS. I found the following issues:

1. code mining is not displayed emidiately. I have to close and reopen the editor for the code minings to be shown
2. Two ZWSP next to each other are drawn one the (almost?) same location. See line 4 in:
<img width="128" alt="image" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/28338612/e52ea190-8f04-4c54-a826-1732696c90a8">
3. When select the "a" and the "ZWSP" in line 2 from the above screenshot to with the keyboard I have to press the right-cursor two times until the caret is behind the "ZWSP".

2023-12-20 07:38 UTC, BeckerWdf commented on bundles/org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/internal/texteditor/codemining/ZeroWidthSpaceLineContentCodeMiningProvider.java
> +	private static final char ZWSP_SIGN = '\u200b';
we should also add
```
\u200c  zero width non-joiner
\u200d  zero width joiner
\ufeff  zero width no break space
```
See: https://plugins.jetbrains.com/plugin/7448-zero-width-characters-locator

2025-08-11 14:25 UTC, marcushoepfner commented on bundles/org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/internal/texteditor/codemining/ZeroWidthSpaceLineContentCodeMiningProvider.java
> +	private static final char ZWSP_SIGN = '\u200b';
I have updated this PR.
It works now with all above zero width characters.

Please check it.
Please also check the new preferences: 
<img width="1009" height="589" alt="image" src="https://github.com/user-attachments/assets/2d13125c-7fee-4732-9f78-d1fd05f59180" />

1. Do we need to distinguish between line begin, end and enclosing for ZWSP? IMHO not, just makes core more complex. But "enclosing" may not fit as a term then.

2. Do we show ZWSP as code mining or something else? Because it is not just space.
<img width="248" height="144" alt="image" src="https://github.com/user-attachments/assets/e4358384-c4db-4ae8-8224-fd3fb451a57f" />

2025-08-13 07:42 UTC, BeckerWdf commented
I manually tested your change.

the ZWSP is shown correctly:
<img width="324" height="178" alt="image" src="https://github.com/user-attachments/assets/1e1a20fa-6e26-479a-8829-4dba963c751d" />

but when I disable the "show whitespace character" function (e.g. via the toolbar button) the ZWSP code mining still not disappears (even though the other "white space character" stuff does correctly disappear:
<img width="538" height="334" alt="image" src="https://github.com/user-attachments/assets/13d44668-50b3-4e47-8f63-1b0ed74cf588" />

2025-08-13 07:43 UTC, BeckerWdf requested changes, later dismissed
See my comments above

2025-08-13 07:46 UTC, BeckerWdf commented
another topic:
a user can change the color of the code minings in the "fonts and colors" preference page. If you do this you will see a mix of colors:

<img width="428" height="322" alt="image" src="https://github.com/user-attachments/assets/72268c52-89a3-42ca-b6fd-12eba3f040ce" />

Maybe this can be improved:
- either by ignoring the users color pref here
- also use the code mining color from preferences for the other "white space character" drawing logic.

2025-10-09 13:05 UTC, marcushoepfner commented
> I manually tested your change.
> 
> the ZWSP is shown correctly: <img alt="image" width="324" height="178" src="https://private-user-images.githubusercontent.com/28338612/477418470-1e1a20fa-6e26-479a-8829-4dba963c751d.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAwMTUzODQsIm5iZiI6MTc2MDAxNTA4NCwicGF0aCI6Ii8yODMzODYxMi80Nzc0MTg0NzAtMWUxYTIwZmEtNmUyNi00NzlhLTg4MjktNGRiYTk2M2M3NTFkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDA5VDEzMDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2M2VhMjExMmZjYTkwNzk4OGMyZWM1MjkwOTZkNGYwMTZlMmZlOTcwMWNhOGFlMjQ5ZmEyOWZlYTljNjhhZjYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.OJcQaRytDXScG3s4BB-R68HlvBr-MDEmYaG2Jp-KzXw">
> 
> but when I disable the "show whitespace character" function (e.g. via the toolbar button) the ZWSP code mining still not disappears (even though the other "white space character" stuff does correctly disappear: <img alt="image" width="538" height="334" src="https://private-user-images.githubusercontent.com/28338612/477418969-13d44668-50b3-4e47-8f63-1b0ed74cf588.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAwMTUzODQsIm5iZiI6MTc2MDAxNTA4NCwicGF0aCI6Ii8yODMzODYxMi80Nzc0MTg5NjktMTNkNDQ2NjgtNTBiMy00ZTQ3LThmNjMtMWIwZWQ3NGNmNTg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDA5VDEzMDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZmMGEwODBlZTEzNGY3YmZiNjlhYTIzZjc3YjdmZGY2MjMxMjU1MDY2N2I2MDBmMTI2MTg4ODYxM2Y1NmZlZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.jgGqmJmAF4s-RdNGc4Q5ojsLeutAcCBaeOllxpKdhdc">

fixed with the last commit.

2025-10-09 13:07 UTC, marcushoepfner commented
> another topic: a user can change the color of the code minings in the "fonts and colors" preference page. If you do this you will see a mix of colors:
> 
> <img alt="image" width="428" height="322" src="https://private-user-images.githubusercontent.com/28338612/477420538-72268c52-89a3-42ca-b6fd-12eba3f040ce.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjAwMTUzODQsIm5iZiI6MTc2MDAxNTA4NCwicGF0aCI6Ii8yODMzODYxMi80Nzc0MjA1MzgtNzIyNjhjNTItODlhMy00MmNhLWI2ZmQtMTJlYmEzZjA0MGNlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDA5VDEzMDQ0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhNjk4YmYxZDBkNjYxNGY3NGZkMGM3Yjg4NjJlMmVhNjFiOWVmOWNlZjM4YmE3YTE5ZmM5Y2E2Yjg0Mzc5OGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.U9XOkKrIxTPR6TYj9wgddlvn0Dw0yY70910zzlKKMxc">
> Maybe this can be improved:
> 
> * either by ignoring the users color pref here
> * also use the code mining color from preferences for the other "white space character" drawing logic.

I tried to ignore and overwrite the color with the one TextEditor uses for drawing spaces, tabs,...
According to https://github.com/eclipse-platform/eclipse.platform.ui/blob/2c5b6056f00e7a012022aa8f5342ed5f97e5a6c1/bundles/org.eclipse.jface.text/src/org/eclipse/jface/text/WhitespaceCharacterPainter.java#L447 this is `SWT.COLOR_LIST_FOREGROUND`, which is black.
I even debugged the drawing of a tab and it was colored 0, 0, 0 but appeared grey. I dont get it....

2025-10-10 14:32 UTC, BeckerWdf commented
I just played around a bit with the current state.
I got this:

```
java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Display.getSystemColor(int)" because the return value of "org.eclipse.swt.widgets.Display.getCurrent()" is null
	at org.eclipse.ui.internal.texteditor.codemining.ZeroWidthCharactersLineContentCodeMining.<init>(ZeroWidthCharactersLineContentCodeMining.java:40)
	at org.eclipse.ui.internal.texteditor.codemining.ZeroWidthCharactersLineContentCodeMiningProvider.createCodeMining(ZeroWidthCharactersLineContentCodeMiningProvider.java:108)
	at org.eclipse.ui.internal.texteditor.codemining.ZeroWidthCharactersLineContentCodeMiningProvider.provideCodeMinings(ZeroWidthCharactersLineContentCodeMiningProvider.java:72)
	at org.eclipse.jface.internal.text.codemining.CodeMiningManager.lambda$2(CodeMiningManager.java:194)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
```

2025-10-13 05:45 UTC, BeckerWdf commented
> fixed with the last commit.

Thanks. That looks good now.

2025-10-13 05:46 UTC, BeckerWdf commented
> I just played around a bit with the current state. I got this:
> 
> ```
> java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Display.getSystemColor(int)" because the return value of "org.eclipse.swt.widgets.Display.getCurrent()" is null
> 	at org.eclipse.ui.internal.texteditor.codemining.ZeroWidthCharactersLineContentCodeMining.<init>(ZeroWidthCharactersLineContentCodeMining.java:40)
> 	at org.eclipse.ui.internal.texteditor.codemining.ZeroWidthCharactersLineContentCodeMiningProvider.createCodeMining(ZeroWidthCharactersLineContentCodeMiningProvider.java:108)
> 	at org.eclipse.ui.internal.texteditor.codemining.ZeroWidthCharactersLineContentCodeMiningProvider.provideCodeMinings(ZeroWidthCharactersLineContentCodeMiningProvider.java:72)
> 	at org.eclipse.jface.internal.text.codemining.CodeMiningManager.lambda$2(CodeMiningManager.java:194)
> 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> ```

This is now also fixed. Thanks,

2025-10-13 05:55 UTC, marcushoepfner commented
> > I just played around a bit with the current state. I got this:
> > ```
> > java.lang.NullPointerException: Cannot invoke "org.eclipse.swt.widgets.Display.getSystemColor(int)" because the return value of "org.eclipse.swt.widgets.Display.getCurrent()" is null
> > 	at org.eclipse.ui.internal.texteditor.codemining.ZeroWidthCharactersLineContentCodeMining.<init>(ZeroWidthCharactersLineContentCodeMining.java:40)
> > 	at org.eclipse.ui.internal.texteditor.codemining.ZeroWidthCharactersLineContentCodeMiningProvider.createCodeMining(ZeroWidthCharactersLineContentCodeMiningProvider.java:108)
> > 	at org.eclipse.ui.internal.texteditor.codemining.ZeroWidthCharactersLineContentCodeMiningProvider.provideCodeMinings(ZeroWidthCharactersLineContentCodeMiningProvider.java:72)
> > 	at org.eclipse.jface.internal.text.codemining.CodeMiningManager.lambda$2(CodeMiningManager.java:194)
> > 	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
> > ```
> 
> This is now also fixed. Thanks,

Is the color of "ZWSP" grey or black in your case?

2025-10-13 05:55 UTC, BeckerWdf commented
> I tried to ignore and overwrite the color with the one TextEditor uses for drawing spaces, tabs,... According to
> 
> https://github.com/eclipse-platform/eclipse.platform.ui/blob/2c5b6056f00e7a012022aa8f5342ed5f97e5a6c1/bundles/org.eclipse.jface.text/src/org/eclipse/jface/text/WhitespaceCharacterPainter.java#L447
> 
> this is `SWT.COLOR_LIST_FOREGROUND`, which is black.
> I even debugged the drawing of a tab and it was colored 0, 0, 0 but appeared grey. I dont get it....

I also just debugged this. And I see that the color (for the whitespace chars comes from the styleRange not the textWidget:

https://github.com/eclipse-platform/eclipse.platform.ui/blob/2c5b6056f00e7a012022aa8f5342ed5f97e5a6c1/bundles/org.eclipse.jface.text/src/org/eclipse/jface/text/WhitespaceCharacterPainter.java#L449

2025-10-13 05:56 UTC, BeckerWdf commented
> Is the color of "ZWSP" grey or black in your case?

black.

2026-01-23 14:03 UTC, tobiasmelcher commented
The `WhitespaceCharacterPainter` uses in the light theme the black color `Color {0, 0, 0, 255}` to draw the invisible characters with `gc.drawString`. It looks greyish because `gc.setAlpha(fAlpha);` is called beforehand with value `fAlpha=80`. 
Here the location where setAlpha is called.

```
private void handleDrawRequest(GC gc, int x, int y, int w, int h) {
		int startLine= fTextWidget.getLineIndex(y);
		int endLine= fTextWidget.getLineIndex(y + h - 1);
		if (startLine <= endLine && startLine < fTextWidget.getLineCount()) {

			// avoid painting into the margins:
			Rectangle clipping= gc.getClipping();
			Rectangle clientArea= fTextWidget.getClientArea();
			int leftMargin= fTextWidget.getLeftMargin();
			int rightMargin= fTextWidget.getRightMargin();
			clientArea.x+= leftMargin;
			clientArea.width-= leftMargin + rightMargin;
			clipping.intersect(clientArea);
			gc.setClipping(clientArea);
			if (fIsAdvancedGraphicsPresent) {
				int alpha= gc.getAlpha();
				gc.setAlpha(fAlpha); // <!------------------------------------
				drawLineRange(gc, startLine, endLine, x, w);
				gc.setAlpha(alpha);
			} else {
				drawLineRange(gc, startLine, endLine, x, w);
			}
			gc.setClipping(clipping);
		}
	}
```
We could do the same in the `ZeroWidthCharactersLineContentCodeMining` so that all whitespaces are rendered in the same color. Maybe introduce a re-usable in `WhitespaceCharacterPainter` to retrieve the color config which can then be reused by the code mining.

2026-01-23 16:30 UTC, tobiasmelcher commented
​[c5d21c1] sets the same color in the ZWSP code minings as it is done in the whitespace character painter

<img width="906" height="346" alt="image" src="https://github.com/user-attachments/assets/d48ac807-7c7e-43d3-9172-485c963ff932" />

2026-01-26 08:29 UTC, tobiasmelcher commented
Unfortunately, the rendering on Windows does currently not look that good compared to MacOS (all screenshots shown above are from MacOS).

Here a Windows screenshot with font Consolas. There is an unwanted gap between ZWSP and the next character.

<img width="896" height="458" alt="zwsp_windows_consolas" src="https://github.com/user-attachments/assets/45e37911-4fa3-4955-872e-e461505a6c17" />

And here a Windows screenshot with font Courier New. The additional width required for the ZWSP code mining is somehow not taken into account.

<img width="912" height="424" alt="zwsp_windows_courier_new" src="https://github.com/user-attachments/assets/19276e00-450f-4dec-94f7-2f6991688a62" />

2026-01-26 17:30 UTC, tobiasmelcher commented
[b76e3d4] solves the rendering problem on windows.

Here a screenshot with the Consolas font on Windows showing the zero width spaces as code minings.
<img width="858" height="372" alt="image" src="https://github.com/user-attachments/assets/5474129f-edc0-4155-92f6-dde4fbe5fb19" />

Here a screenshot with the Courier New font on Windows showing the zero width spaces as code minings.
<img width="913" height="363" alt="image" src="https://github.com/user-attachments/assets/d12fa7e2-aaae-4487-afd5-a1d8dc88d86e" />

Here a screenshot with the Monospace font on Linux (Suse) showing the zero width spaces as code minings.
<img width="1097" height="524" alt="image" src="https://github.com/user-attachments/assets/7f412912-5d91-4572-a184-9a2c85515821" />

2026-01-27 07:54 UTC, BeckerWdf commented
> [[b76e3d4](https://github.com/eclipse-platform/eclipse.platform.ui/commit/b76e3d488521146008cd3f150f47419488b6b757)] solves the rendering problem on windows.

Does it make sense to extract this to an own PR. I assume that we could reproduce this error without this new feature in the whitespace drawer.

2026-02-12 08:40 UTC, BeckerWdf commented
don't merge master in your feature branch - we cannot merge these. Pls. rebase your feature branch on top of master.

2026-02-12 08:47 UTC, marcushoepfner commented
> don't merge master in your feature branch - we cannot merge these. Pls. rebase your feature branch on top of master.

argh, sorry. It's been a while... :)

2026-02-12 09:09 UTC, BeckerWdf commented
Is this PR in "draft" state by intention?

2026-02-12 09:23 UTC, marcushoepfner commented
> Is this PR in "draft" state by intention?

It is ready-for-review now.
Draft for me means, we still working on it. And that was the case until this morning.

2026-02-12 12:47 UTC, marcushoepfner commented
Interesting, the current version in main branch is 3.20

But the API warning says something about 3.19...

<img width="1607" height="279" alt="image" src="https://github.com/user-attachments/assets/601cd600-c07b-4f43-9fd0-c06316fb34e9" />

I "just" added a new public constant. Why is this considered a broken API? Guess going for 4.0.0 is not an option here :)

2026-02-12 13:11 UTC, iloveeclipse commented
> Interesting, the current version in main branch is 3.20

And that is the problem
 
> But the API warning says something about 3.19...

Because we don't increase minor version **twice** for the same release. It was already bumped in 5f6cae670b3885523d18c0d2bbf84022da0aa650.

So please undo the version increment in manifest and change since tag to 3.20.
After that there will be still API error on `org.eclipse.ui.texteditor.AbstractTextEditor.PREFERENCE_SHOW_ZW_CHARACTERS`, and you can add a filter for this error in the editor via Ctrl+1.

Also would be good if you could squash all commits to a single one and after that rebase on latest master branch.

2026-02-12 13:13 UTC, iloveeclipse commented
But honestly speaking, today is last day for API changes (tomorrow is M3), I don't expect this change qualifies for RC builds, therefore you can keep on the version bump anyway but do the rest and wait for review comments & merge in the next SDK release.

2026-03-02 14:05 UTC, marcushoepfner commented
> > Interesting, the current version in main branch is 3.20
> 
> And that is the problem
> 
> > But the API warning says something about 3.19...
> 
> Because we don't increase minor version **twice** for the same release. It was already bumped in [5f6cae6](https://github.com/eclipse-platform/eclipse.platform.ui/commit/5f6cae670b3885523d18c0d2bbf84022da0aa650).
> 
> So please undo the version increment in manifest and change since tag to 3.20. After that there will be still API error on `org.eclipse.ui.texteditor.AbstractTextEditor.PREFERENCE_SHOW_ZW_CHARACTERS`, and you can add a filter for this error in the editor via Ctrl+1.
> 
> Also would be good if you could squash all commits to a single one and after that rebase on latest master branch.

I don't see the quickfix/error.
I used 2026-03 RC2 as baseline and did not change any settings. I can even see that org.eclipse.ui.workbench.texteditor already has one filter.

Is there any documentation on how to setup the baseline?
I followed the [help](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fapi_tooling_baseline.htm), but it did not solve my problem.
[Contributing.md ](https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md) does not contain information regarding baseline setup. I wonder why not, as this seems to be an essential step in Eclipse contribution.

2026-03-03 06:36 UTC, marcushoepfner commented
> > > Interesting, the current version in main branch is 3.20
> > 
> > 
> > And that is the problem
> > > But the API warning says something about 3.19...
> > 
> > 
> > Because we don't increase minor version **twice** for the same release. It was already bumped in [5f6cae6](https://github.com/eclipse-platform/eclipse.platform.ui/commit/5f6cae670b3885523d18c0d2bbf84022da0aa650).
> > So please undo the version increment in manifest and change since tag to 3.20. After that there will be still API error on `org.eclipse.ui.texteditor.AbstractTextEditor.PREFERENCE_SHOW_ZW_CHARACTERS`, and you can add a filter for this error in the editor via Ctrl+1.
> > Also would be good if you could squash all commits to a single one and after that rebase on latest master branch.
> 
> I don't see the quickfix/error. I used 2026-03 RC2 as baseline and did not change any settings. I can even see that org.eclipse.ui.workbench.texteditor already has one filter.
> 
> Is there any documentation on how to setup the baseline? I followed the [help](https://help.eclipse.org/latest/index.jsp?topic=%2Forg.eclipse.pde.doc.user%2Ftasks%2Fapi_tooling_baseline.htm), but it did not solve my problem. [Contributing.md ](https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md) does not contain information regarding baseline setup. I wonder why not, as this seems to be an essential step in Eclipse contribution.

@merks Can you help here?

2026-03-09 08:16 UTC, merged

2026-03-10 06:18 UTC, iloveeclipse commented
This change introduces memory leak, please check https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2856.

2026-03-10 07:19 UTC, BeckerWdf commented
@marcushoepfner: Can you pls. have a look?

2026-03-10 08:09 UTC, marcushoepfner commented
It seems that the dipose call on CodeMiningProviders is completely missing from text editor.
Only Java does it for its own providers in `JavaEditor.dispose()`

2026-03-10 08:15 UTC, BeckerWdf commented
> JavaEditor.dispose()

So you say it's not a regression of this PR but this PR only did uncover and pre-existing issue?

2026-03-10 08:17 UTC, marcushoepfner commented
> > JavaEditor.dispose()
> 
> So you say it's not a regression of this PR but this PR only did uncover and pre-existing issue?

Seems so. I have a local solution already and will create a PR later.
Code Mining "experts" need to check it then.

2026-03-10 08:19 UTC, BeckerWdf commented
> Code Mining "experts" need to check it then.

We can ask @tobiasmelcher to review it.

2026-03-10 09:18 UTC, marcushoepfner commented
Provided a fix in #3770 .
Let's stop the discussion here and move over to #3770 and https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/2856.

2026-05-18 08:38 UTC, BeckerWdf commented
@marcushoepfner: Should we add this to the New & Noteworthy document?

2026-05-18 08:40 UTC, marcushoepfner commented
> @marcushoepfner: Should we add this to the New & Noteworthy document?

Oh yes. Any documentation on how to do that?

2026-05-18 08:46 UTC, BeckerWdf commented
> Oh yes. Any documentation on how to do that?

It's about editing https://github.com/eclipse-platform/www.eclipse.org-eclipse/blob/master/news/4.40/platform.md