Jenkinsfile: disable javadoc, maven issues
eclipse-platform/eclipse.platform.ui pull request #1557
Opened 2024-01-25 11:13 UTC by jukzi

- publishAllIssues: false - to disable unrelated warnings in PRs
- maven: wrongly collects "API WARNING"s without resolving filename
- javadoc: it is currently not used

* eclipse: ecj info markers work fine with parsing xml files

2024-01-25 11:22 UTC, jukzi commented
@laeubi @akurtakov @HannesWell @iloveeclipse 
let's disable the not correctly working plugins on all repos,  and be happy that at least ecj works now reliably (thanks @laeubi). If adding other plugins again please make sure they are working fine, collecting the right thinks.

2024-01-25 11:41 UTC, akurtakov commented
I can see that Maven one is generating too much noise and is not actionable quite often . But why disable the javadoc one? IMHO it catches cases that would otherwise fail the I-build and has no false positives, I know it's not catching all issues but it prevents a good chunk of them..

2024-01-25 11:44 UTC, jukzi commented
> know it's not catching all issues but it prevents a good chunk of them..

i have not seen it catching any javadoc issue even though there are javadoc issues. until now i have only seen javadoc issues reported by ecj - handled by eclipse() plugin

2024-01-25 11:49 UTC, laeubi commented
> maven: wrongly collects "API WARNING"s without resolving filename

Why is this "wrong", it does not can show the warnings on the file but still it is to be fixed (I'm currently working on generating a ecj like xml file from API warnings [here](https://github.com/eclipse-tycho/tycho/pull/3379)).

> I can see that Maven one is generating too much noise and is not actionable quite often 

PDE is down to one maven warning that I currently can't understand (it reports a difference in classfile that I can't reproduce locally) but beside that they are actionable....

> i have not seen it catching any javadoc issue even though there are javadoc issues. until now i have only seen javadoc issues reported by ecj - handled by eclipse() plugin

ECJ does not handle javadoc quite well:
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1858
- https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1582

2024-01-25 11:50 UTC, laeubi commented
> publishAllIssues: false - to disable unrelated warnings in PRs

They are not unrelated they show where we have warnings that might be fixed as part of a PR.

2024-01-25 11:54 UTC, jukzi commented
> Why is this "wrong", it does not can show the warnings on the file but still it is to be fixed (I'm currently working on generating a ecj like xml file from API warnings [here](https://github.com/eclipse-tycho/tycho/pull/3379)).

It gathers locations in the "console Output" instead of pointing to the offending .java file. As a result it randomly interprets those errors as "new" or "old" dependinig on the line number  in the console output - which is almost random, since each commit can modify output lenght.
As soon you have a working solution we can enable that, but for now its just broken.

2024-01-25 11:56 UTC, jukzi commented
> They are not unrelated they show where we have warnings that might be fixed as part of a PR.

As soon as they fixed by the PR, then they are not shown. if you are interested in Warnings that could be fixed you can simply go to jenkins or problems view to see all existing ones. But there is no need to pollute every PR with that information.m Nobody reads that and even less people actually fix them.

2024-01-25 11:59 UTC, laeubi commented
> It gathers locations in the "console Output" instead of pointing to the offending .java file. As a result it randomly interprets those errors as "new" or "old" dependinig on the line number in the console output - which is almost random, since each commit can modify output lenght.

That's wrong, these warnings are always there, they are just not visible most of the time as the API tools are skipped when the baseline replace kicks in (for performance reasons).

> As soon you have a working solution we can enable that, but for now its just broken.

It is the best we can offer with a home brew API tools solution that no one else in the industry seem to use...

> But there is no need to pollute every PR with that information.m Nobody reads that and even less people actually fix them.

If nobody is reading them there can't be an issue in showing them...

2024-01-25 12:00 UTC, laeubi requested changes
Disabling warnings just because they annoy people is a no-go for me. Without showing problems they won't get fixed.

2024-01-25 12:06 UTC, jukzi commented
> Disabling warnings just because they annoy people is a no-go for me. Without showing problems they won't get fixed.

they are not disabled, they still visible in the console log. Only that PRs are not polluted with unrelated or false positives.

> If nobody is reading them there can't be an issue in showing them...

They are visible and distract from real related issues. They are annoying even if you don't read them. like popups/disclaimer you never read but accept blindly.

2024-01-25 12:24 UTC, iloveeclipse commented
> Only that PRs are not polluted with unrelated or false positives.

I've expressed many times my opinion on this, and I agree that one should not enable additional checks **on PR's** as long as the checked issues are not fixed and so all PR's marked as "failed" because of the (unrelated) checks.

I appreciate work on fixing warnings, but this work should not interfere with regular work and should not confuse contributors.

**A PR that makes a change that builds & run tests without introducing new warnings or errors should be always green.**

If it is not, and additionally because of unrelated code, it only confuses everyone. Also people learn to ignore all kind of PR validation errors because "they are always there".

> let's disable the not correctly working plugins on all repos

Could you please link some examples of recent PR's with false positives?

2024-01-25 12:33 UTC, jukzi commented
> Could you please link some examples of recent PR's with false positives?

Currently all PRs are affected to show the issues stated in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1557#issue-2100146979. That does not mean they are "red", but the details shown in the jenkins/ github PR are disturbing  - or even wrong.

2024-01-25 14:53 UTC, akurtakov commented
@jukzi 
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/574788/a0a6eb26-9419-4cfd-9b49-94349a97dd8e)
from https://ci.eclipse.org/platform/job/eclipse.platform.ui/job/PR-1558/2/ shows a warning catched by javadoc plugin that is not catched by ecj plugin. I hope this is good enough proof.

2024-01-25 15:16 UTC, jukzi commented
it finds a warning and can not relate it to any file in the repository .. i hope that is proof enough that it is not helpfull


```
12:58:17.281 [INFO] --- javadoc:3.6.3:jar (attach-javadocs) @ org.eclipse.jface ---
12:58:17.668 [INFO] No previous run data found, generating javadoc.
12:58:27.922 [WARNING] Javadoc Warnings
12:58:27.922 [WARNING] /home/jenkins/agent/workspace/eclipse.platform.ui_PR-1558/bundles/org.eclipse.jface/src/org/eclipse/jface/action/Action.java:28: warning: empty <p> tag
12:58:27.922 [WARNING] * <p>
12:58:27.922 [WARNING] ^
...
[JavaDoc] [-ERROR-] Can't create fingerprints for some files:
[JavaDoc] [-ERROR-] - '12:58:27.922 [WARNING] /home/jenkins/agent/workspace/eclipse.platform.ui_PR-1558/bundles/org.eclipse.jface/src/org/eclipse/jface/action/Action.java' file not found
[JavaDoc] [-ERROR-] Can't create fingerprints for some files:
[JavaDoc] [-ERROR-] - '12:58:27.922 [WARNING] /home/jenkins/agent/workspace/eclipse.platform.ui_PR-1558/bundles/org.eclipse.jface/src/org/eclipse/jface/action/Action.java' file not found
```

=> warning not shown on github:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/5f9c7403-10ff-40d2-87f0-10dcd66c93a8)

2024-01-25 15:29 UTC, laeubi commented
> it finds a warning and can not relate it to any file in the repository ..

Sometimes I really get the impression people "don't see it" because they _don't want to see it_:

![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/c171b124-637f-442b-8c24-5135b4cab19d)

![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/6a5cb20b-7261-42f1-87f6-0c85ae3d0077)

2024-01-25 15:33 UTC, jukzi commented
the numbers are correct, but the warning it is supposed to be shown in the review tab like every ecj marker. somehow it is not configured right.  i suggest you get it fully working before enabling it

2024-01-25 15:35 UTC, akurtakov commented
@jukzi So showing a warning (no false positives found so far) with a direct link to the code line is considered not helpful because not rendered in Github UI . 
I simply give up here.

2024-01-25 15:38 UTC, laeubi commented
> A PR that makes a change that builds & run tests without introducing new warnings or errors should be always green.



> the numbers are correct, but the warning it is supposed to be shown in the review tab like every ecj marker. somehow it is not configured right. i suggest you get it fully working before enabling it

Sorry to say but that's nonsense, code annotations are a completely different topic, so your claim it does not find issues is simply proven wrong so please stop to invent new argument of "not working".

2024-01-25 15:38 UTC, jukzi commented
> I simply give up here.

And that's the problem with this tools: only half configured it would stay that way until the end. Instead you could try to fix that error. May be it would be enough to convert absolute path to a relative one.

2024-01-25 15:41 UTC, laeubi commented
> May be it would be enough to convert absolute path to a relative one.

I already told you several times, _if you suspect a bug or improvement_ the please report it here: https://github.com/jenkinsci/warnings-ng-plugin "we" can't do anything here (only if the bug is fixed to ask infrateam to update Jenkins).

2024-01-25 15:43 UTC, jukzi commented
Thats exactly the mood i don't like: installing something broken and leave the cleanup for others.

2024-01-25 16:12 UTC, laeubi commented
> Thats exactly the mood i don't like: installing something broken and leave the cleanup for others.

The difference is just the interpretation of "broken" ... for me it is nothing broken and I can perfectly work with it (and it seems you even used that in the past PRs) now it is suddenly "broken" for you ... 

So for me the problem is more searching "fly in the ointment" than actually aiming for something to improve.

2024-01-25 16:29 UTC, jukzi commented
I have not used that tools. in opposite: i am steady confused by them - for example javadoc telling me there are no issues while there are. For javadoc the one and only way is to grep the console log manually. 
Or maven constantly telling me new issues introduced while nothing changed.

2024-01-25 16:43 UTC, akurtakov commented
This is not leading anywhere. 
As per https://github.com/eclipse-platform/.github/wiki/PMC-project-guidelines#committer-disagreement-resolution I step up as a PL and ask you @jukzi to ask for vote on the topic on platform-dev. That would help us understand how majority of committers feel about the tooling and its usefulness. 
I deliberately skip steps from the process and ask for the vote directly for the already explained reason. So far I see 3 options:
* disable maven (some non actionable/resolvable warnings) and javadoc (no such but GH/Jenkins UI not rendering annotations)
* disable only maven(due to non actionable/resolvable warnings)
* disable none (report all warnings even as they warn about possible problems)

2024-01-25 16:49 UTC, akurtakov commented
I actually took the liberty to experiment with GH polls https://github.com/eclipse-platform/eclipse.platform.ui/discussions/1567 .  Everyone, please feel free to fix the wording on the poll, I tried to be as objective as I could in the options.

2024-01-26 05:17 UTC, laeubi commented
> javadoc telling me there are no issues while there are. For javadoc the one and only way is to grep the console log manually.

Please share an example, on the other hand why are you not "steady confused" and we should not disable ECJ warnings then as it tells there are not javadoc issues [while there are](https://github.com/eclipse-jdt/eclipse.jdt.core/issues/1858) some?

> Or maven constantly telling me new issues introduced while nothing changed.

I have opened
- https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/1747

2024-01-27 06:13 UTC, laeubi commented
@vogella just as we [have talked about here](https://github.com/eclipse-platform/eclipse.platform.ui/discussions/1567#discussioncomment-8255782) (but I don't want to spam the thread more so I think its fine to continue here!)

I mentioned here a problem with the display of the status:
- https://github.com/jenkinsci/warnings-ng-plugin/pull/1649#issuecomment-1895154647

The user gracefully opened a PR here:
- https://github.com/jenkinsci/github-branch-source-plugin/pull/757

What one can see as of today:
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/ba74c461-fa01-403d-836d-6c998768e769)

Really amazing!

2024-01-27 06:22 UTC, laeubi commented
By the way API issues will not no longer be reported as Maven warnings / errors but listed in the ECJ issues:

![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/5c2c92fc-c0d5-41ed-b588-18b266680c1c)

Also shown as code annotations here:

![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/1331477/dc3a5e71-8210-4bd2-9830-89812328a732)

And as I assume it is "super confusing" I'll propose to rename the check from "Eclipse Compiler" to "Eclipse Compiler and API problem" soon, **please let me know if you prefer a different naming**...

2024-02-13 16:15 UTC, closed without merging