Mark COPY_LINE_UP and COPY_LINE_DOWN as state dependent
eclipse-platform/eclipse.platform.ui pull request #1876
Opened 2024-05-07 13:28 UTC by rubenporras

2024-05-07 13:32 UTC, iloveeclipse commented
@rubenporras : could you please describe the problem you are trying to fix?

2024-05-08 06:31 UTC, rubenporras commented
We found that the "copy lines up" and "copy lines down" commands are disabled in our editors, and we found that this is because the editor is not modifiable when it is created. The commands do not become enabled when the editor does become modifiable, which happens once the file being edited is synchronized.

The solution is to mark this commands state dependent, as other similar commands such as move line up/down or the different cut line variants (and others just see the lines which are close to my additions).

2024-05-08 06:37 UTC, iloveeclipse commented
@rubenporras : thanks. 
Could you please amend your commit and provide a proper commit message with that information. 
See https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#commit-message-recommendations
After that please rebase it on latest master state and force push your commit to the github.

2024-05-08 08:18 UTC, fedejeanne requested changes
> @rubenporras : thanks. Could you please amend your commit and provide a proper commit message with that information. See https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#commit-message-recommendations After that please rebase it on latest master state and force push your commit to the github.

@rubenporras a proper commit message is not a copy-paste of the description of this PR, it's rather something that can be quickly understood while reading the history. Something like:

```
Make COPY_LINE_UP/DOWN and JOIN_LINES commands state dependent

This will (de)activate them accordingly together with the editor.
```

Please reword it

2024-05-08 08:51 UTC, fedejeanne approved these changes

2024-05-08 10:00 UTC, rubenporras commented
Thanks for the review. Could we merge it?

2024-05-08 10:57 UTC, merged