Add ability to Pin PopupDialog
eclipse-platform/eclipse.platform.ui pull request #1906
Opened 2024-05-31 14:26 UTC by mickaelistria

In some circumstances (eg comparisons), users may want PopopDialogs to remain visible when switching attention to another area. This introduces a "Pin dialog" menu (and a "Close") to allow the dialog to stick when users selects it.

Fixes https://github.com/eclipse-platform/eclipse.platform.ui/issues/1905

2024-06-03 06:12 UTC, jukzi submitted a review, later dismissed
The user can not know which Window belongs to which context

2024-06-03 07:49 UTC, mickaelistria commented
> The user can not know which Window belongs to which context

Indeed, and it would be nice to improve it some time. But still this improvement is helpful, doesn't harm standard usage nor the code.
So while things can -as always- be improved, for example by adding titles to pop-ups or more content in them, this cannot be a standard implementation in JFace anyway.
So I don't think your feedback can be fairly treated as a blocker. @eclipse-platform/eclipse-platform-project-leads Can some PLs please discuss here?

2024-06-03 08:18 UTC, iloveeclipse requested changes
Few issues with the current PR:
1) **Major one** It changes menu for **every** popup dialog, even for those who probably never intended to be "pinned". I'm not sure 
2) On Linux it doesn't work as expected: once focus is lost, pinned dialog is closed (tried with the Quick Type Hierarchy).
3) The menu text is not added to properties file.
4) The checkbox "pinned" state seem to be persisted. Not sure this is intended, as "pinning" is most likely needed only for special occasions, not by default.
5) Since pinning doesn't work for me I can't test how it would behave with multiple dialogs.

So far the major change I would expect here: this feature should be optional and client code should decide if it should be turned on.

2024-06-03 08:28 UTC, mickaelistria commented
> Major one It changes menu for every popup dialog, even for those who probably never intended to be "pinned". I'm not sure

Indeed, but actually, it may be occasionally useful be able to pin any pop-up dialog. Think about Ctrl+3  when you don't remember what you want to type in an need to close then reopen, or when using JDT open symbols.
It's not a very common use-case, but it can always be a helpful one.

> On Linux it doesn't work as expected: once focus is lost, pinned dialog is closed (tried with the Quick Type Hierarchy).

OK, that's strange as I tested it works. But I will retry it with Quick Type hierarchy to make sure.

> The menu text is not added to properties file.

Missing `git add`, sorry. I'll fix it.

2024-06-03 09:08 UTC, mickaelistria commented
The "Quick Text Hierarchy" seems to be a very particular case, it's actually the HierarchyInformationControl which itself implements JDT's AbstractInformationControl . This control seems to *not* close the dialog when clicking out, but instead just makes it invisible and reopens it later if it wasn't really closed (eg closed with Esc or an element got selected).

2024-06-03 09:16 UTC, iloveeclipse commented
> The "Quick Text Hierarchy" seems to be a very particular case

But this is an example of custom code that doesn't need "pin/close" actions and where adding actions that don't do anything would be understood as a bug by users. That is yet another reason to make the new code optional.

2024-06-03 09:18 UTC, mickaelistria commented
ok.

2024-06-03 09:31 UTC, mickaelistria commented
I've pushed a new patch taking an extra constructor flag.

2024-06-03 10:24 UTC, mickaelistria commented
see consumer: https://github.com/eclipse-platform/eclipse.platform/pull/1403

2024-06-05 15:08 UTC, iloveeclipse commented
PR needs a rebase before merge anyway.

2024-06-05 15:15 UTC, iloveeclipse commented
Just quickly scanning through the code it seem OK. Couldn't test as the second PR can't be rebased on master.

2024-06-10 07:50 UTC, mickaelistria commented
@iloveeclipse I'd like to merge this soon. Any issue left?

2024-06-10 08:46 UTC, jukzi commented
I am against this CR!  the only proposed usecase does not work and i see no benefit over just seeing the values in the debug shell (press ctrl+shift d twice):
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/58715b2a-a6e7-4b2d-a88a-fe3b49ff53f3)

2024-06-10 09:01 UTC, mickaelistria commented
>  the only proposed usecase

I think this can have merits for many, if not all popup dialogs. As it could allow to eg easily compare Type hierarchies and so on. But it requires adoption from consumers to enable more use-cases. At least, this PR makes things possible.

> does not work

As demoed in https://github.com/eclipse-platform/eclipse.platform/pull/1403 , this works, at least in some cases; that may not be all of them, but at least cover the initial story that brought to this contribution (comparing values from 2 distinct executions).
Let's continue the discussion about the case that work/don't work in https://github.com/eclipse-platform/eclipse.platform/pull/1403 .

>  i see no benefit over just seeing the values in the debug shell 

That's because your example here only deals with "flat" objects which have a nice `toString()` implemented. Debugging often requires to inspect more complex objects for which just printing is not the most efficient.

2024-06-10 09:16 UTC, jukzi commented
> > i see no benefit over just seeing the values in the debug shell
> 
> That's because your example here only deals with "flat" objects which have a nice `toString()` implemented. Debugging often requires to inspect more complex objects for which just printing is not the most efficient.

For objects without toString() you can use the Expressions view (ctrl+shit+i twice):
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/a5116235-65c6-4eb9-be5c-261283eb4d07)
the popups are not any better.

2024-06-10 09:23 UTC, mickaelistria commented
> For objects without toString() you can use the Expressions view (ctrl+shit+i twice):

To be honest, I didn't know that it was possible to send an "evaluated" expression to this view. I always type code in so this gets re-evaluated on every context change.
So indeed, this can cover a part of this story.
Still...

> the popups are not any better.

They are often more usable to me, because they allow side by side comparison of values as trees, which is crucial in many cases.

2024-06-11 08:00 UTC, mickaelistria commented
@jukzi I think all your concerns about working or not and overall usability/usefulness were covered. Anything else?

2024-06-11 08:07 UTC, iloveeclipse commented on bundles/org.eclipse.jface/src/org/eclipse/jface/messages.properties
> +PopupDialog.pinDialog = &Pin dialog
`dialog` -> `Dialog`

2024-06-11 08:08 UTC, iloveeclipse approved these changes
Please fix action name, the rest looks OK

2024-06-11 08:14 UTC, mickaelistria commented on bundles/org.eclipse.jface/src/org/eclipse/jface/messages.properties
> +PopupDialog.pinDialog = &Pin dialog
Done.

2024-06-11 08:28 UTC, jukzi commented
I tested it again. Closing with key shortcut works now. The related text in the pop up is wrong.  
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/f473d28d-91da-474e-843e-0ad31b0b74e2)
crtl-shift-i does not move but close the pop up. And when having multiple pop ups i now have multiple such "help" texts, Which are not helpfull at all, as only the active popup can use that key. So i suggest on pinning the popup that text is removed.

The main difference to pinning a value to the expression view is that pop ups don't close when the debugee is terminated. Which leads to VMDisconnectedException when using a pinned popup:
![image](https://github.com/eclipse-platform/eclipse.platform.ui/assets/51790620/7cad8b77-b4e4-4490-bee1-74026d25e38e)
Also there is nothing like "close-all" for popups so that it is hard to clean up the screen. 
In summary i highly dislike the whole workflow of using that menu to pin ,move and close the popup. It's much easier to just configure a screenshot tool like greenshot and take screenhots of the popup with a hotkey. So i would never use the Pin functionality myself. On the other hand that workflow is so well hidden that no normal user would ever find or use it anyway, so that it won't be a harm and i am not strictly against it. But is there anybody beside you who actually want's this unhandy feature?

2024-06-11 08:43 UTC, mickaelistria commented
> crtl-shift-i does not move but close the pop up

I think it's more a topic for https://github.com/eclipse-platform/eclipse.platform/pull/1403 , but I'll try to make it work as this can be useful.

> Which leads to VMDisconnectedException when using a pinned popup:

IMO, this is acceptable. Auto-closing a pinned dialog would semantically be incorrect. Keeping the dialog open and having such message showing its content are outdated is consistent with expectation.

> Also there is nothing like "close-all" for popups so that it is hard to clean up the screen.

I don't think it's a major issue, and it's for sure not a regression. It would moreover be difficult to know what "Close All" mean: class all inspect windows, close all inspect windows for the current launch, close all pop-up dialogs...

> But is there anybody beside you who actually want's this unhandy feature?

I know that many people want a more efficient way to compare values from different stackframes/launches. I don't claim this is the perfect way, but I think it's a better way than everything we have so those people would be happy to use it.

> that it won't be a harm

Indeed.

2024-06-11 09:14 UTC, merged