[Sticky Scrolling] Fix separator color on windows
eclipse-platform/eclipse.platform.ui pull request #1967
Opened 2024-06-14 08:44 UTC by Christopher-Hermann

The separator in the sticky lines controls are drawn in a bad color on windows dark theme. With this change, the separator color is aligned with the theme.

Current coloring on windows:
<img width="929" alt="Bildschirmfoto 2024-06-14 um 10 42 22" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/79514265/1725a976-8bdd-4a34-91f6-dcefc9bb0b03">

How it should look like:
<img width="484" alt="Bildschirmfoto 2024-06-14 um 10 43 20" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/79514265/7eaff78e-9f82-4b0b-b229-2216204099a3">

This is a follow up for #1894

2024-06-14 08:45 UTC, Christopher-Hermann commented
@Wittmaxi could you please check if this solves the issue on windows dark theme? If not, I need to set the correct background color for the separator.

2024-06-14 08:57 UTC, BeckerWdf commented
> This is a follow up for #1894

You meant point "1" in https://github.com/eclipse-platform/eclipse.platform.ui/pull/1894#issuecomment-2158291505 ?

2024-06-14 09:03 UTC, Christopher-Hermann commented
> You meant point "1" in [#1894 (comment)](https://github.com/eclipse-platform/eclipse.platform.ui/pull/1894#issuecomment-2158291505) ?

Yes, correct. Linking the comment is actually a good idea :)

2024-06-14 11:20 UTC, Wittmaxi commented
![grafik](https://github.com/eclipse-platform/eclipse.platform.ui/assets/16443184/6ec44ba0-eecf-4e47-9528-f942c4cb0d66)

This is what I see, so no, I Would not consider this a fix. I tried to play around with different color values but I could not find a good fix.
I primarily use dark mode, so I would really appreciate you fixing this :) - thanks for putting in the effort!

2024-06-14 11:28 UTC, Christopher-Hermann commented
> I tried to play around with different color values but I could not find a good fix. 

Could you try to set the color for both separator in StickyLinesControl line 180:
`bottomSeparator.setBackground(Display.getDefault().getSystemColor(SWT.COLOR_WIDGET_LIGHT_SHADOW));
`

2024-06-14 11:40 UTC, Wittmaxi commented
@Christopher-Hermann this is precisely what I tried (well, with another color) - it had no effect on the bars for me.

2024-06-14 11:45 UTC, Christopher-Hermann commented
> @Christopher-Hermann this is precisely what I tried (well, with another color) - it had no effect on the bars for me.

Okay, damn you SWT :D Then I need to check on my virtual machine if I can reproduce the error to find a solution. 
But it's really strange, I assume that other separators are colored correctly on Windows dark theme.

2024-06-14 11:49 UTC, Wittmaxi commented
@Christopher-Hermann Yes, I have had regular issues with SWT in the past - the dark theme seems to be especially prone to bugs and inconsistencies ;_;

2024-07-05 10:48 UTC, Christopher-Hermann commented
Changed the implementation since I did not manage to color the separator on windows. Now a composite with background color is used:
<img width="899" alt="Bildschirmfoto 2024-07-05 um 12 42 47" src="https://github.com/eclipse-platform/eclipse.platform.ui/assets/79514265/dd9b4873-b3d8-43d8-a032-fd6a84cc6af3">

I tested on Windows and MacOS, both are working. But I would be grateful for further testers

2024-07-05 11:22 UTC, BeckerWdf approved these changes
Tested on macOS: Looks good.

2024-07-05 11:24 UTC, BeckerWdf commented
> "summary": "Eclipse Platform 4.33 M1 Promotion",

I thought that M1 is a milestone without freeze period. Am I wrong?

2024-07-05 11:37 UTC, vogella commented
I think all our milestones are without freezes these days. @akurtakov can you update us on the latest state of freezing stuff?

2024-07-05 11:39 UTC, Christopher-Hermann commented
> Tested on macOS: Looks good.

I found one more issue, the CSS Color Engine is overwriting the background color of the separator composite. I need to check how I can disable the CSS Engine for this composite.

2024-07-05 11:41 UTC, akurtakov commented
> I think all our milestones are without freezes these days. @akurtakov can you update us on the latest state of freezing stuff?

Milestones don't have freezes but there is still the "promotion" day in the calendar (so everyone can see when it is) and the script checking it https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/42b625b2b0e971e1147761a7473e55170a3f5504/.github/workflows/verifyFreezePeriod.yml#L22 doesn't distinguish between M, RC and R promotion thus we end up with this freezes during M promotion days. It would be nice if someone enhances the script to not complain for milestone promotions.

2024-07-05 11:43 UTC, vogella commented
> > I think all our milestones are without freezes these days. @akurtakov can you update us on the latest state of freezing stuff?
> 
> Milestones don't have freezes but there is still the "promotion" day in the calendar (so everyone can see when it is) and the script checking it https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/42b625b2b0e971e1147761a7473e55170a3f5504/.github/workflows/verifyFreezePeriod.yml#L22 doesn't distinguish between M, RC and R promotion thus we end up with this freezes during M promotion days. It would be nice if someone enhances the script to not complain for milestone promotions.

Create https://github.com/eclipse-platform/eclipse.platform.ui/issues/2040 for this.

2024-07-05 13:46 UTC, vogella commented
> > Tested on macOS: Looks good.
> 
> I found one more issue, the CSS Color Engine is overwriting the background color of the separator composite. I need to check how I can disable the CSS Engine for this composite.

We have a css tag for this. See https://www.vogella.com/tutorials/Eclipse4CSS/article.html#ignore-certain-widgets-during-styling

2024-07-07 07:36 UTC, Christopher-Hermann commented
> We have a css tag for this. See https://www.vogella.com/tutorials/Eclipse4CSS/article.html#ignore-certain-widgets-during-styling

Thanks a lot, this did the trick.

2024-07-07 10:02 UTC, vogella commented
> > I think all our milestones are without freezes these days. @akurtakov can you update us on the latest state of freezing stuff?
> 
> Milestones don't have freezes but there is still the "promotion" day in the calendar (so everyone can see when it is) and the script checking it https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/42b625b2b0e971e1147761a7473e55170a3f5504/.github/workflows/verifyFreezePeriod.yml#L22 doesn't distinguish between M, RC and R promotion thus we end up with this freezes during M promotion days. It would be nice if someone enhances the script to not complain for milestone promotions.

This should be fixed now by @sratz

2024-07-09 13:40 UTC, Christopher-Hermann commented
The PR is ready for review/merging from my side.

2024-07-09 14:12 UTC, BeckerWdf requested changes

2024-07-09 14:12 UTC, BeckerWdf commented on bundles/org.eclipse.ui.editors/src/org/eclipse/ui/internal/texteditor/ITextEditorThemeConstants.java
> +	/**
this seems to be a copy&past error

2024-07-09 14:25 UTC, Christopher-Hermann commented on bundles/org.eclipse.ui.editors/src/org/eclipse/ui/internal/texteditor/ITextEditorThemeConstants.java
> +	/**
Done, thanks for spotting this

2024-07-09 14:28 UTC, BeckerWdf requested changes

2024-07-09 14:28 UTC, BeckerWdf commented on bundles/org.eclipse.ui.editors/src/org/eclipse/ui/internal/texteditor/ITextEditorThemeConstants.java
> +	 * Theme constant for the color used to render the sticky lines separator"</code>).
```suggestion
	 * Theme constant for the color used to render the sticky lines separator").
```

2024-07-09 14:29 UTC, Christopher-Hermann commented on bundles/org.eclipse.ui.editors/src/org/eclipse/ui/internal/texteditor/ITextEditorThemeConstants.java
> +	 * Theme constant for the color used to render the sticky lines separator"</code>).
Ups, done :)

2024-07-09 14:32 UTC, BeckerWdf approved these changes

2024-07-12 11:57 UTC, BeckerWdf commented
@Christopher-Hermann 
Can you pls. rebase and resolve conflicts?

2024-07-12 12:11 UTC, Christopher-Hermann commented
> @Christopher-Hermann Can you pls. rebase and resolve conflicts?

Done.

2024-07-12 12:53 UTC, BeckerWdf commented
failed this as already known in https://github.com/eclipse-platform/eclipse.platform.ui/issues/926

2024-07-12 12:55 UTC, merged