case-sensitive file existence check
eclipse-platform/eclipse.platform.ui pull request #1984
Opened 2024-06-18 15:04 UTC by andrew-tram

Check to address - https://github.com/eclipse-platform/eclipse.platform.ui/issues/1866

2024-06-18 15:09 UTC, jukzi requested changes
A filesystem may be case sensitive. Mostly depends on OS

2024-06-18 15:16 UTC, andrew-tram commented
@jukzi , good call! I adjusted the checks to account for OS

2024-06-18 15:18 UTC, jukzi requested changes, later dismissed
please do not explicitly check for OS but use any existing function to compare files for equality.

2024-06-18 15:24 UTC, andrew-tram commented
Understood, hopefully this is closer...

```
	    // Use workspace and resource APIs to handle file comparison
	    IWorkspaceRoot root = ResourcesPlugin.getWorkspace().getRoot();
	    IPath newFilePath = getContainerFullPath().append(getFileName());
	    IFile newFileHandle = createFileHandle(newFilePath);

	    IFile[] files = root.findFilesForLocationURI(newFileHandle.getLocationURI());
	    for (IFile file : files) {
	        if (file.exists() && file.getName().equalsIgnoreCase(newFileHandle.getName()) &&
	                !file.getName().equals(newFileHandle.getName())) {
	            setErrorMessage(NLS.bind(IDEWorkbenchMessages.ResourceGroup_nameExistsDifferentCase, file.getName()));
	            return false;
	        }
	    }
```

2024-06-18 15:31 UTC, jukzi commented
You should not need to compare Strings yourself.

2024-06-18 15:49 UTC, merks commented
I’d expect to see IFile or IPath to be compared which know whether to do case-sensitive comparisons.

2024-06-18 15:59 UTC, andrew-tram commented
I believe this is closer to what yall are suggesting...

```
// Use workspace and resource APIs to handle file comparison
IPath newFilePath = getContainerFullPath().append(getFileName());
IFile newFileHandle = createFileHandle(newFilePath);

try {
	IContainer parentContainer = newFileHandle.getParent();
	IResource[] members = parentContainer.members();
	for (IResource member : members) {
		if (member.getType() == IResource.FILE) {
			IPath memberPath = member.getFullPath();
			if (memberPath.equals(newFilePath)) {
				continue; // Skip if it's the same path
			}
			if (memberPath.lastSegment().equalsIgnoreCase(newFileHandle.getName()) &&
					!memberPath.lastSegment().equals(newFileHandle.getName())) {
				setErrorMessage(NLS.bind(IDEWorkbenchMessages.ResourceGroup_nameExistsDifferentCase, member.getName()));
				return false;
			}
		}
	}
} catch (CoreException e) {
	setErrorMessage("Error while validating file name: " + e.getMessage());
	return false;
}
```

Will externalize the new string if all is good.

2024-06-18 16:53 UTC, merks commented
I think you should test it.   I think memberPath.equals(newFilePath) will return true for two paths with different cases on a case-insensitive file system.  I think you if want to check if two paths have different case, you should compare the strings.  So if the paths are equal but the string representation are not equal, then what's specified is different from what's present.  And that problem can be the case for the any segment of the path (project/folder), not just the final segment.

2024-06-18 18:48 UTC, andrew-tram commented
Ive tested this on Windows 11 and Mac 14.4.1 (default HFS+ or APFS in case-insensitive mode). The expected results look good where an error displays saying the file already exists with the same name, different case.

Trying Linux now.

2024-06-18 21:03 UTC, andrew-tram commented
So, I'm not entirely sure how it's feasible to do this without checking for at least if it's Linux.

2024-06-19 00:14 UTC, jwflicker commented
If this approach becomes a challenge, a smaller, targeted fix might be to not selectAndReveal the file and open it an editor if it what is returned from `mainPage.createNewFile()` doesn't exist.

[BasicNewFileResourceWizard](https://github.com/eclipse-platform/eclipse.platform.ui/blob/master/bundles/org.eclipse.ui.ide/src/org/eclipse/ui/wizards/newresource/BasicNewFileResourceWizard.java#L96C17-L96C30):
```
	@Override
	public boolean performFinish() {
		IFile file = mainPage.createNewFile();
		if (file == null) {
			return false;
		}
```
 mainPage.createNewFile() will trigger the display of the error message dialog showing "A resource exists with a different case", but it will return a non-null File object whose .exists() method would return false, but is not checked before invoking `IDE.openEditor(page, file, true);` just below
 
So perhaps just changing `if (file == null) {` to `if (file == null || !file.exists()) {` would dullen the bulk of the annoyance.

2024-06-19 05:33 UTC, jukzi commented
You are supposed to find an existing method of signature
`boolean equals(IFile, IFile)` or `boolean equals(IPath, IPath)` which does the OS check for you. I dont know its place or name by heart but am sure you can find many of them.
Even java.nio.Path.equals(Path) probably does it if the Path is constructed using the appropriate FileSystem.

2025-08-13 14:16 UTC, closed without merging