Workbench restart is available if --launcher.noRestart is used
eclipse-platform/eclipse.platform.ui pull request #2125
Opened 2024-07-23 12:25 UTC by dhendriks

This new argument just got added. See https://github.com/eclipse-equinox/equinox/pull/595. Here we make sure the workbench understands it.

Should be rare that people actually use the option and start the IDE, as it is not meant for that. This PR detects it and informs the user restart is not available, as documented (see https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/pull/2195).

I haven't tested it. Not sure how to build a new IDE with Equinox I-build and this PR both included.

2024-07-28 15:27 UTC, HannesWell requested changes
> I haven't tested it. Not sure how to build a new IDE with Equinox I-build and this PR both included.

To test this you can for example create a new `Eclipse Application` launch configuration based on Features and only add the `org.eclipse.sdk` feature. Then in the arguments tab you can simply add `--launcher.noRestart` as program argument.

I have made some comments below for a few enhancements.
In general instead of informing the user via a Error-Dialog or an error log entry just an `UnsupportedOperationException` could be thrown. But the current variant is probably more friendly.

In order to disable the File -> Restart menu entry you should also add the following constructor to `org.eclipse.ui.internal.handlers.RestartWorkbenchHandler`:
```
	public RestartWorkbenchHandler() {
		setBaseEnabled(E4Workbench.canRestart());
	}
```

2024-07-28 15:27 UTC, HannesWell commented on bundles/org.eclipse.e4.ui.workbench/src/org/eclipse/e4/ui/workbench/IWorkbench.java
> +	 *
This `IWorkbench` interface, similar to the other one is marked with `@noimplement`, which means that only Eclipse itself is supposed to implement it and downstream consumers should not implement it (it is not enforced, but strongly discouraged not to do it).

Therefore I suggest to not mention the launcher option here and at the other `IWorkbench` and just leave these two interfaces unchanged.
In general I assume that this option is only used rarely in UI applications (it's actually not intended to be used then) and therefore we should only add reference to it where really necessary, to no complicate the usual cases.

2024-07-28 15:27 UTC, HannesWell commented on bundles/org.eclipse.e4.ui.workbench/src/org/eclipse/e4/ui/internal/workbench/E4Workbench.java
> +	}
```suggestion
	public static boolean canRestart() {
		String commands = System.getProperty("eclipse.commands", ""); //$NON-NLS-1$ //$NON-NLS-2$
		String NO_RESTART_ARGUMENT = "--launcher.noRestart"; //$NON-NLS-1$
		return commands.lines().map(String::strip).noneMatch(NO_RESTART_ARGUMENT::equals);
	}
```

2024-07-28 15:27 UTC, HannesWell commented on bundles/org.eclipse.e4.ui.workbench/src/org/eclipse/e4/ui/internal/workbench/E4Workbench.java
> +			String message = "Can't restart the workbench, because the --launcher.noRestart argument is used."; //$NON-NLS-1$
```suggestion
			String message = "Can't restart the workbench. This application was started with the '--launcher.noRestart' argument."; //$NON-NLS-1$
```

2024-07-28 15:27 UTC, HannesWell commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/messages.properties
> +Workbench_CantRestart_Title = Restart Unavailable
```suggestion
Workbench_CantRestart_Title = Restart unavailable
```

2024-07-28 15:27 UTC, HannesWell commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/messages.properties
> +Workbench_CantRestart_Message = Can't restart the workbench, since the '--launcher.noRestart' argument was used when starting the application.
```suggestion
Workbench_CantRestart_Message = Can't restart the workbench. This application was started with the '--launcher.noRestart' argument.\n\
Shutdown and start again manually.
```

2024-07-28 15:27 UTC, HannesWell commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/Workbench.java
> +		if (returnCode == PlatformUI.RETURN_RESTART && !canRestart()) {
```suggestion
		if (returnCode == PlatformUI.RETURN_RESTART && !E4Workbench.canRestart()) {
```

2024-07-28 15:27 UTC, HannesWell commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/Workbench.java
> +		if (!canRestart()) {
```suggestion
		if (!E4Workbench.canRestart()) {
```

2024-07-28 15:27 UTC, HannesWell commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/Workbench.java
> +		if (!canRestart()) {
```suggestion
		if (!E4Workbench.canRestart()) {
```

2024-07-28 15:27 UTC, HannesWell commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/Workbench.java
> +
We can just re-use the method from `E4Workbench`
```suggestion
```

2024-07-29 10:27 UTC, dhendriks commented
> > I haven't tested it. Not sure how to build a new IDE with Equinox I-build and this PR both included.
> 
> To test this you can for example create a new `Eclipse Application` launch configuration based on Features and only add the `org.eclipse.sdk` feature. Then in the arguments tab you can simply add `--launcher.noRestart` as program argument.

Is there a specific Oomph setup for Eclipse UI? Will that then pull in the latest I-build with the new launcher?

> I have made some comments below for a few enhancements. In general instead of informing the user via a Error-Dialog or an error log entry just an `UnsupportedOperationException` could be thrown. But the current variant is probably more friendly.

Indeed, that was the idea. I kept it.

> In order to disable the File -> Restart menu entry you should also add the following constructor to `org.eclipse.ui.internal.handlers.RestartWorkbenchHandler`:
> 
> ```
> 	public RestartWorkbenchHandler() {
> 		setBaseEnabled(E4Workbench.canRestart());
> 	}
> ```

The problem with that, is that a user doesn't know *why* it is disabled. Hence, I opted to keep it enabled, but instead give a message to the user that explains why it can't be completed.

2024-07-29 10:28 UTC, dhendriks commented
I made all the changes, as best I could. I squashed the commit. Ready for next review.

2024-07-29 10:44 UTC, merks commented
This setup is a bit overkill that it includes everything 

https://github.com/eclipse-platform/.github/blob/main/CONTRIBUTING.md#creating-an-eclipse-development-environment

but if you back up the wizard to the Projects page you can deselect projects you don’t need/want.  It installs the nightly Ibuild and populates the target platform with that as well.

2024-07-29 13:06 UTC, dhendriks commented
I broke some import statements, but fixed them now.

2024-07-29 13:13 UTC, dhendriks commented
File -> Restart works correctly:

![image](https://github.com/user-attachments/assets/9ed720db-9fdc-46b5-8a09-085b95d5eaf9)

2024-07-29 13:22 UTC, laeubi commented
> File -> Restart works correctly:

I must confess that from a Users Experience Point of View it does not work correctly.

If the action is not available it should either:

1. not shown at all * - or -*
2. disabled with a proper tooltip text

2024-07-29 13:59 UTC, dhendriks commented
> > File -> Restart works correctly:
> 
> I must confess that from a Users Experience Point of View it does not work correctly.

It works as designed, but apparently you're looking for a different design.

> If the action is not available it should either:
> 
> 1. not shown at all  _- or -_
> 2. disabled with a proper tooltip text
> 
> Also the message is to much technical for a user to understand (too much information) and unlikely to be actionable.

Not showing it has the downside that a user then does not know why it is not shown, when normally it is shown. Similar with disabling it, as was [suggested before](https://github.com/eclipse-platform/eclipse.platform.ui/pull/2125#pullrequestreview-2203516183). You suggest it is possible to disable, but have a tooltip text that explains why it is not shown? That would be nice. But, I've never heard of special disabled text tooltips. How does one set those?

2024-07-29 16:19 UTC, laeubi commented
> Not showing it has the downside that a user then does not know why it is not shown, when normally it is shown.

It depends, there are many things that are not shown in Eclipse, so this is the usual behavior. At least I have never used this Restart function anyways in > 10 years of Eclipse so some even won't notice that.
In combination with this option needing specifically be enabled and requiring to know what it does anyways it does not sounds like anything harmful to hide it completely in such case.

In contrast to that, I now get a hard to understand error popup that indicates I should remove the option I carefully have put into my product configuration before... but why have I put it there if I want to support restarts?!?

>  You suggest it is possible to disable, but have a tooltip text that explains why it is not shown? 

Yes, I have not checked if its possible.

2024-07-29 17:34 UTC, dhendriks commented
I've disabled the File -> Restart in case the option is given:

![image](https://github.com/user-attachments/assets/4b7a30db-403a-4bfc-825e-2443bcbde966)

2024-07-29 21:50 UTC, HannesWell approved these changes
Thank you @dhendriks for the update and of course this PR in general.

> In contrast to that, I now get a hard to understand error popup that indicates I should remove the option I carefully have put into my product configuration before... but why have I put it there if I want to support restarts?!?

I also agree that first of all we should preventing restarts from being possible. A dedicated tool-tip for the disabled state would of course be nice in this case, but with the given use-case I think it's also fine to not have it.
As we already said in the very beginning the new `--launcher.noRestart` option is not intended for UI applications anyway. And if one stil adds them to a config, that person should remember that we noticing the disabled Restart entry. And if still someone adds that option to a product those devs should probably take care on their own to handle it better (e.g. add the tool-tip too).

Even though restart is now disabled if that option is present there can still be cases where the dialog can pop-up. I'm fine with that (again since it should actually not be used I'm also fine with a not 100% perfect solution) but tried to further enhance the readability of the text in the dialog.

With that I'm fine with this change. If there are no objections I'll submit this tomorrow evening.

2024-07-30 06:40 UTC, dhendriks commented
> [...] tried to further enhance the readability of the text in the dialog.

I changed the logged message in `E4Workbench` to again be the same as the one from the dialog.

2024-07-30 19:19 UTC, HannesWell commented
> > [...] tried to further enhance the readability of the text in the dialog.
> 
> I changed the logged message in `E4Workbench` to again be the same as the one from the dialog.

Thanks. Also for all your contributions on this topic. It was great work. If you are interested in contributing more to Eclipse, that would be welcome. :)

2024-07-30 19:19 UTC, merged