TextSearchVisitor: don't check for binary files if not required
eclipse-platform/eclipse.platform.ui pull request #2215
Opened 2024-08-23 07:43 UTC by Wittmaxi

If a workspace search is allowed to search in binary files, we should not perform a (possibly expensive) check for whether a file is binary - we are going to search through it regardless of the result of that query.

As discussed in
https://github.com/eclipse-platform/eclipse.platform.ui/issues/2180

Note: the performance increase is not yet optimal - we still load the file to ram, the difference is that now, we don't scan through the file for zero-bytes. A "good" solution would recognize file extensions and not load those files to begin with.

2024-08-23 11:20 UTC, jukzi commented
> A "good" solution would recognize file extensions and not load those files to begin with.

performance optimizations should show the benefit by measurement, and please lets go for a "good" solution - opening a file is typically the costly thing while reading the content is almost not noticeable if its in the OS cache.

2024-08-26 08:14 UTC, laeubi approved these changes
Looks good to me, this is obviously an improvement as the check for binary file is the one that most likely more costly than that of asking the collector if it wants binary content.

2024-08-26 13:19 UTC, Wittmaxi commented
@jukzi my current focus is finishing up the tasks in the Umbrella issue for the Find/Replace overlay. I understand that this is more of a "low hanging fruit"-PR, I might be able to come up with a real improvement in a few months - and yet, I can't commit to anything at this point.

If this is OK for you, I will merge this PR once master opens up again

2024-08-26 14:06 UTC, jukzi requested changes
If you can provide a measurement that shows the benefit i am good with it. But please never ever merge a performance improvement without a measurement. We have way too many regressions by such well-intentioned commits having bad side effect.

My guess is `fCollector.reportBinaryFile(file)` will return false. i.e. the inverse of that is true i.e. you do not change anything with this commit.

2024-08-26 14:09 UTC, laeubi commented
@jukzi please read the PR description for what case this is meant:

> If a workspace search is allowed to search in binary files,

So this is for the case where searching in binary files is **enabled**, meaning even if we want to search in binary files (currently second check!) it is first heck if it is a binary file just to the discard the result because we want to search in *Every file* regardless if binary or not...

2024-10-16 12:48 UTC, closed without merging

2024-10-16 12:49 UTC, Wittmaxi commented
I cannot take ownership of this anymore. I believe I have seen another PR which fixed this already, so this PR is obsolete