Change to font colors of sel/unsel tabs and also highlight
eclipse-platform/eclipse.platform.ui pull request #2286
Opened 2024-09-17 10:19 UTC by mvm-sap

Font color of all tabs - selected/ unselected/ not in focus, have been changed to black to have better contrast. Also, selected tab with inactive view will have grey highlight, selected tab with active view will still continue to have blue highlight.
Please find the below screen shots:

Before:
![image](https://github.com/user-attachments/assets/a3f491f9-5027-40da-a19d-256c13debfd2)

![image](https://github.com/user-attachments/assets/9679aef3-9d37-4abc-8520-d9b5b0cd820a)

After:

![image](https://github.com/user-attachments/assets/6a26f8e0-d5d8-4e5c-8e7c-bb5870a6a6d3)

![image](https://github.com/user-attachments/assets/4f4da26b-b1fb-4533-a72f-1afab7759f5a)

2024-09-17 10:45 UTC, BeckerWdf commented
pls provide two PRs for the two things:
- 1 PR for the font color stuff
- 1 PR for the blue / grey underline-stuff

2024-09-17 12:10 UTC, BeckerWdf requested changes
adaptions to the macOS and the gtk version of the theme is missing.

2024-09-17 12:51 UTC, BeckerWdf commented
> adaptions to the macOS and the gtk version of the theme is missing.

This is fixed now. Looks good on macOS.

2024-09-17 12:55 UTC, BeckerWdf requested changes
I think a version bump is needed to the org.eclipse.ui.themes plugin's MANIFEST.MF.
Pls. add is as a separate commit (title e.g. "Version bumps for 4.34 stream")

2024-09-17 15:30 UTC, mvm-sap commented
> pls provide two PRs for the two things:
> 
> * 1 PR for the font color stuff
> * 1 PR for the blue / grey underline-stuff

This PR has changes related to tab higlight

2024-09-18 06:21 UTC, mvm-sap commented
> I think a version bump is needed to the org.eclipse.ui.themes plugin's MANIFEST.MF. Pls. add is as a separate commit (title e.g. "Version bumps for 4.34 stream")

Done

2024-09-18 06:34 UTC, BeckerWdf approved these changes

2024-09-18 07:20 UTC, BeckerWdf commented
failing verification jobs seem unrelated.

2024-09-18 07:20 UTC, merged