Added "Close mode" frame in editor preference
eclipse-platform/eclipse.platform.ui pull request #2298
Opened 2024-09-19 09:16 UTC by praveen-skp

Issue: #2297 

This pull request adds a "Close mode" frame in the editor preference to make the "Close editors automatically" and "Number of opened editors before closing" grouping clear.

2024-09-19 09:17 UTC, praveen-skp commented
![Close mode](https://github.com/user-attachments/assets/8a4ed342-bd19-44e7-9c70-ef32782925c1)

The new UI with "Close mode" grouping

2024-09-19 09:41 UTC, laeubi commented
`Close mode` as a group name reads a bit strange here, I would expect then having different modes to select but the configuration do not really offer that.

My suggestion would be to merge both settings into one line instead of grouping them e.g.

`[ ] Close oldest if there are more than _____ editors open`

2024-09-19 10:44 UTC, BeckerWdf commented
> `Close mode` as a group name reads a bit strange here

What about "Closing behaviour"?

2024-09-19 10:46 UTC, BeckerWdf commented
> My suggestion would be to merge both settings into one line instead of grouping them

This is also a good idea.

2024-10-04 05:59 UTC, praveen-skp commented
This is how the new UI looks.
![Disabled](https://github.com/user-attachments/assets/d3d19e34-da6f-4528-86d7-271540e082a8)
![Enabled](https://github.com/user-attachments/assets/0c055b5e-75f1-4c24-aee2-c494e48f34e5)

2024-10-04 06:10 UTC, BeckerWdf commented
Can the input field made shorter so that the line doesn't get too long. I think place for around 4 chars would be sufficient.

What about changing the text to: "Close oldest editor if there more then ... editor open"

What does "oldest" mean? 
a) The one that was open the longest time, or 
b) the one where the time of last use is most far in the past?

2024-10-08 03:53 UTC, praveen-skp commented
I checked the current behaviour and noticed that it's not always the oldest editors that are being closed.

### Use case 1:
If I have the following editors opened in order:
1, 2, 3, 4, 5, 6 (1 being the oldest, focus is on 6)

- Set editor limit to 3
- Open editor 7
- The current available editors are 7, 2, 3

It deletes the latest 3 editors (6, 5, 4) and replaces the oldest editor.

---

### Use case 2:
If I have the following editors opened in order:
1, 2, 3, 4, 5, 6 (1 being the oldest, focus is on 5)

- Set editor limit to 3
- Open editor 7
- The current available editors are 7, 2, 3

It deletes the latest 3 editors (5, 6, 4) and replaces the oldest editor (1).

---

### Use case 3:
If I have the following editors opened in order:
1, 2, 3, 4, 5, 6 (1 being the oldest, focus is on 2)

- Set editor limit to 3
- Open editor 7
- The current available editors are 7, 3, 4

It deletes the latest 3 editors (2, 6, 5) and replaces the oldest editor (1).

---

### Use case 4:
If I have the following editors opened in order:
1, 2, 3 (1 being the oldest, focus is on 3)

- Set editor limit to 3
- Open editor 4
- The current available editors are 4, 2, 3

It replaces the oldest editor (1).

---

### Use case 5:
If I have the following editors opened in order:
1, 2, 3 (1 being the oldest, focus is on 1)

- Set editor limit to 3
- Open editor 4
- The current available editors are 1, 4, 3

It replaces the oldest editor (2).

2024-10-08 03:55 UTC, praveen-skp commented
It looks like its not always the oldest editors that are being closed. 
So shall we change the text to something generic like: 
Close editor(s) if there are more than ... editors open

2024-10-08 09:30 UTC, BeckerWdf commented
> Close editor(s) if there are more than ... editors open

yes.

2024-10-08 09:30 UTC, BeckerWdf commented
> > Close editor(s) if there are more than ... editors open
> 
> yes. Maybe  without the () simply "Close editors if..."

2024-10-09 03:18 UTC, praveen-skp commented
![Reduced size](https://github.com/user-attachments/assets/6eb958b5-f6bf-46f0-af46-674e620f6b31)

Reduced the size of the input field to show two characters, to match the text limit of 2 characters in the code.

2024-10-10 08:55 UTC, BeckerWdf commented
merge commit are not allowed in PR. Can you pls. squash and rebase on top of current master please?

2024-10-11 11:04 UTC, BeckerWdf requested changes

2024-10-11 11:04 UTC, BeckerWdf commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/messages.properties
> +WorkbenchPreference_closeMode=Close mode
we don't need this text any more. Pls. remove it here and from the messages class

2024-10-11 11:14 UTC, BeckerWdf commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/messages.properties
> +WorkbenchPreference_closeMode=Close mode
id did remove it

2024-10-11 11:15 UTC, BeckerWdf approved these changes
I plan to merge this once CI-Build is happy

2024-10-11 11:56 UTC, merged