Modify the 'Close Active Editors' (plural) handler to add support for…
eclipse-platform/eclipse.platform.ui pull request #2360
Opened 2024-10-03 13:09 UTC by feilimb

Modify the 'Close Active Editors' (plural) handler to add support for parts which represent an Editor and have been contributed via eg. PartDescriptors in a Model Fragment. 

See also, the recent and similar PR: https://github.com/eclipse-platform/eclipse.platform.ui/pull/2315

Associated with Issue#2176.

@mickaelistria - just tagging you here since you were good enough to review the other related PR recently (2315).

2024-10-08 14:22 UTC, jukzi commented
Can you please add a junit test?

referenced issue: https://github.com/eclipse-platform/eclipse.platform.ui/issues/2176

2024-10-08 16:01 UTC, feilimb commented
> Can you please add a junit test?

@jukzi Certainly I can try - would there any pre-existing tests in the area of editor opening/closing (ideally compatibility layer plus E4 part descriptor fragment contribution) that you could point me towards as a starting point of reference?

2024-10-08 16:13 UTC, jukzi commented
sorry i am not familiar with e4, but you may look around in `package org.eclipse.ui.tests.e4;`

2024-10-10 11:49 UTC, feilimb commented
@jukzi JUnit test added now, hopefully it is sufficient for what needs to be covered

2024-10-10 11:55 UTC, jukzi commented on tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/e4/CloseAllHandlerTest.java
> + * @since 3.5
no "since" in tests please

2024-10-10 11:55 UTC, jukzi commented on tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/e4/CloseAllHandlerTest.java
> +package org.eclipse.ui.tests.e4;
copyright missing

2024-10-10 11:56 UTC, jukzi commented on tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/e4/DummyEditor.java
> + * Copyright (c) 2010 IBM Corporation and others.
update year, author company

2024-10-10 11:56 UTC, jukzi commented on tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/e4/DummyEditor.java
> + *     IBM Corporation - initial API and implementation
company or author

2024-10-10 11:57 UTC, jukzi commented on tests/org.eclipse.e4.ui.tests/src/org/eclipse/e4/ui/tests/application/CloseActiveEditorsTest.java
> +//
not outcommented code please

2024-10-10 11:57 UTC, jukzi commented on tests/org.eclipse.e4.ui.tests/src/org/eclipse/e4/ui/tests/application/CloseActiveEditorsTest.java
> + * Copyright (c) 2009, 2017 IBM Corporation and others.
fix header

2024-10-10 11:59 UTC, jukzi commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/CloseAllHandler.java
> +	 * <p>
please remove "<p></p>" - html formatted javdoc on private code is a waste, people will only read the comment.

2024-10-10 12:01 UTC, jukzi commented on tests/org.eclipse.ui.tests/Eclipse UI Tests/org/eclipse/ui/tests/e4/CloseAllHandlerTest.java
> +		/**
remove needless `{@inheritDoc}`

2024-10-10 12:02 UTC, jukzi requested changes
some minor code style issues only

2024-10-10 13:38 UTC, feilimb commented
Code style & copyright block changes applied, hopefully I caught everything there.

2024-10-10 14:06 UTC, jukzi approved these changes
LGTM, lets wait a bit if someone else wants to review / test

2024-10-10 15:08 UTC, feilimb commented
Merged all commits into one, and rebased branch - to see if the Workflows fare better.

2024-10-22 10:08 UTC, feilimb commented
> LGTM, lets wait a bit if someone else wants to review / test

@jukzi there has been no more inputs on this PR in the meantime, do you think it would be possible to land it at this point?

2024-10-22 11:24 UTC, merged

2024-10-23 05:03 UTC, akurtakov commented
New test seems to be unstable failed (at least):
* https://download.eclipse.org/eclipse/downloads/drops4/I20241022-1800/testresults/html/org.eclipse.ui.tests_ep434I-unit-cen64-gtk3-java23_linux.gtk.x86_64_23.html 
* https://download.eclipse.org/eclipse/downloads/drops4/I20241022-1800/testresults/html/org.eclipse.ui.tests_ep434I-unit-cen64-gtk3-java17_linux.gtk.x86_64_17.html