Impl #2402 - Migrate model processors from extension point to OSGi DS
eclipse-platform/eclipse.platform.ui pull request #2403
Opened 2024-10-15 08:01 UTC by fipro78

2024-10-19 10:50 UTC, HannesWell requested changes
Thanks for this one the change itself looks sound, but if I start an SDK from my workspace with it the start-up fails:

```
org.eclipse.e4.core.di.InjectionException: Unable to process "BindingService.manager": no actual value was found for the argument "BindingManager".
	at org.eclipse.e4.core.internal.di.InjectorImpl.reportUnresolvedArgument(InjectorImpl.java:462)
	at org.eclipse.e4.core.internal.di.InjectorImpl.resolveRequestorArgs(InjectorImpl.java:453)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalInject(InjectorImpl.java:128)
	at org.eclipse.e4.core.internal.di.InjectorImpl.internalMake(InjectorImpl.java:386)
	at org.eclipse.e4.core.internal.di.InjectorImpl.make(InjectorImpl.java:312)
	at org.eclipse.e4.core.contexts.ContextInjectionFactory.make(ContextInjectionFactory.java:203)
	at org.eclipse.ui.internal.Workbench$31.runWithException(Workbench.java:2337)
	at org.eclipse.ui.internal.StartupThreading$StartupRunnable.run(StartupThreading.java:35)
	at org.eclipse.swt.widgets.Synchronizer.syncExec(Synchronizer.java:183)
	at org.eclipse.ui.internal.UISynchronizer.syncExec(UISynchronizer.java:133)
	at org.eclipse.swt.widgets.Display.syncExec(Display.java:4883)
	at org.eclipse.ui.internal.StartupThreading.runWithoutExceptions(StartupThreading.java:93)
	at org.eclipse.ui.internal.Workbench.initializeDefaultServices(Workbench.java:2331)
	at org.eclipse.ui.internal.Workbench.init(Workbench.java:1714)
	at org.eclipse.ui.internal.Workbench.runUI(Workbench.java:2825)
	at org.eclipse.ui.internal.Workbench.lambda$3(Workbench.java:632)
	at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:339)
	at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:546)
	at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:173)
	at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:175)
	at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:208)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:143)
	at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:109)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:439)
	at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:271)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:662)
	at org.eclipse.equinox.launcher.Main.basicRun(Main.java:598)
	at org.eclipse.equinox.launcher.Main.run(Main.java:1441)
	at org.eclipse.equinox.launcher.Main.main(Main.java:1414)
```

My first guess is that `ModelAssembler` somehow registers contributions through OSGi services differently. I already tried to process services before extensions, but that didn't help. I can further look into this, but probably not before next week-end.

2024-10-19 10:52 UTC, HannesWell commented
And regarding your remark in https://github.com/eclipse-platform/eclipse.platform.ui/pull/2396#issuecomment-2413177986
> And btw the service attribute on the @Component in your snippet is not necessary, as it is derived from the implements IModelProcessorContribution. So actually the information is redundant. Just in case you wonder why I have not used it in my PR.

That's right, but using it explicitly was a suggestion from @laeubi to ensure that services don't get implemented 'accidentally' if for example later another interface is implemented that's not intended as service. And I think that's reasonable.

2024-10-19 13:34 UTC, laeubi commented
> That's right, but using it explicitly was a suggestion from @laeubi to ensure that services don't get implemented 'accidentally' if for example later another interface is implemented that's not intended as service. And I think that's reasonable.

Its actually a bit different and why I think actually specify it always is good on the long term:

1. Assume you implement *no interface* then your component gets immediately activated
2. Later you let it implement an interface then it is no longer getting activated unless the interface is actually fetched as a service

Other case:

1. Assume you implement *two interface* then your component gets registered as that service
2. Later you implement let it derive from a base class and remove that interface it is no longer registered as such service, or you choose to implement an extension of such interface

So actually if one relies on the default, it means one must check each time something is refactored there, because of this I simply always add it explicitly so its always clear and less prone to accidental changes.

2024-10-21 05:52 UTC, fipro78 commented
For the service attribute discussion, well from the maintenance point of view I understand this. Fine for me. And actually necessary to fix the issue.

About the issue, well we now have a startup order issue. The `BindingToModelProcessor` requires the `ContextToModelProcessor` and the `CommandToModelProcessor` the be executed before. Otherwise the necessary instances in the context are not yet available.

I see the following two errors in the logs:

```
!ENTRY org.eclipse.ui 4 4 2024-10-21 06:45:41.953
!MESSAGE Command manager was null in org.eclipse.ui.internal.BindingToModelProcessor

!ENTRY org.eclipse.ui 4 4 2024-10-21 06:45:41.987
!MESSAGE Context manager was null in org.eclipse.ui.internal.BindingToModelProcessor
```

I have now added a Condition service to describe the activation order dependency. With the extension points this was done by registering the extensions in the correct oder in the plugin.xml.

2024-10-21 05:54 UTC, laeubi commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/BindingToModelProcessor.java
> +	Condition commandAndContextCondition;
Why not simply use two references here instead? This looks a bot over complicated.

2024-10-21 06:01 UTC, akurtakov commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/CommandAndContextCondition.java
> +package org.eclipse.ui.internal;
Missing license header.

2024-10-21 08:28 UTC, fipro78 commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/BindingToModelProcessor.java
> +	Condition commandAndContextCondition;
Well, we could replace the condition reference with the [Satisfying Condition](https://docs.osgi.org/specification/osgi.cmpn/8.0.0/service.component.html#service.component-satisfying.condition) Component Annotation later on when DS 1.5 works with PDE DS Annotation Support. And there would be then no never used members in the class that might confuse others.

But yes, probably only syntactic sugar. I will update it for two directly and never used references.

2024-10-21 08:59 UTC, laeubi commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/BindingToModelProcessor.java
> +	Condition commandAndContextCondition;
Maybe add a comment why these are fetched (but not used) otherwise someone might remove them later on.

2024-10-21 09:29 UTC, fipro78 commented on bundles/org.eclipse.ui.workbench/Eclipse UI/org/eclipse/ui/internal/BindingToModelProcessor.java
> +	Condition commandAndContextCondition;
Already done with the latest change ;)

2024-11-06 23:47 UTC, HannesWell reviewed
Thank you for the update and sorry for the late reply.
The change looks good and worked well in my testing.

But please squash your three commits into one with a commit message covering the resulting change, there is no need to effectively capture the review discussion in the git-history (you remove the version bump and let the bot add it again).
Then this is ready from my side.

2024-11-07 19:40 UTC, HannesWell approved these changes
Thank you for the updates and this change in general.
The code looks good, now only the build has to succeed.

2024-11-07 21:50 UTC, HannesWell commented
Test failure it's unrelated, submitting.

Thanks again!

2024-11-07 21:50 UTC, merged