[Dark Theme] Fix for highlight issue in sub-tabs
eclipse-platform/eclipse.platform.ui pull request #2639
Opened 2024-12-19 17:44 UTC by mvm-sap

With the dark theme changes, selected sub-tabs in the editor and views were missing blue highlights. This has been fixed with this PR. The screenshots below are from Windows. The same change has been incorporated in Mac and Linux.

Before:
![Screenshot 2024-12-19 231102](https://github.com/user-attachments/assets/3fe65df1-0226-4afe-bc09-ad799d74a14e)

After:
![Screenshot 2024-12-19 225628](https://github.com/user-attachments/assets/5f9905c8-4f4c-4fd6-9414-f97ace8ae070)

2024-12-23 09:34 UTC, BeckerWdf requested changes
I manually tested this. Works fine an fixes the bug.

I see that the changes are the same on all 3 platforms (CSS rules are identical).
Can't we then simply move this into the e4-dark_globalstyle.css only once instead of duplicating it three times?

2024-12-23 09:36 UTC, mvm-sap commented
> I manually tested this. Works fine an fixes the bug.
> 
> I see that the changes are the same on all 3 platforms (CSS rules are identical). Can't we then simply move this into the e4-dark_globalstyle.css only once instead of duplicating it three times?

Okay, I shall try to move and test again

2024-12-23 09:42 UTC, BeckerWdf commented
> I manually tested this. Works fine an fixes the bug.
> 
> I see that the changes are the same on all 3 platforms (CSS rules are identical). Can't we then simply move this into the e4-dark_globalstyle.css only once instead of duplicating it three times?

of in `e4-dark_tabstyle.css`

2024-12-27 10:30 UTC, BeckerWdf commented
The current state of the PR does not work correctly on macOS:
<img width="825" alt="image" src="https://github.com/user-attachments/assets/4da7ef15-5c3a-4786-afa7-77e4b3dd1c9c" />

2024-12-27 10:31 UTC, BeckerWdf requested changes
does not work on macOS

2025-01-03 09:32 UTC, mvm-sap commented
> does not work on macOS

I'm not sure why it isn't working. Shall I revert to a previous commit that made changes in all three platforms and worked fine? I don't have a MAC to test or debug, hence the problem.

2025-01-03 09:39 UTC, BeckerWdf commented
It's only the last change moving it to a common file that did not work. Your initial commit worked.

2025-01-03 09:42 UTC, mvm-sap commented
> It's only the last change moving it to a common file that did not work. Your initial commit worked.

Shall I revert it back to the changes done in initial commit ?

2025-01-03 09:44 UTC, BeckerWdf commented
> > It's only the last change moving it to a common file that did not work. Your initial commit worked.
> 
> Shall I revert it back to the changes done in initial commit ?

yes

2025-01-03 10:38 UTC, mvm-sap commented
> > > It's only the last change moving it to a common file that did not work. Your initial commit worked.
> > 
> > 
> > Shall I revert it back to the changes done in initial commit ?
> 
> yes

Could you please test again and confirm if its working?

2025-01-03 12:31 UTC, BeckerWdf approved these changes

2025-01-03 12:31 UTC, BeckerWdf commented
Works fine on macOS

2025-01-03 15:11 UTC, merged