Move o.e.jface.tests to Java 17
eclipse-platform/eclipse.platform.ui pull request #575
Opened 2023-02-09 15:55 UTC by vrubezhny

2023-02-09 16:30 UTC, akurtakov reviewed
Please make sure that equals tests still stay calling equals.

2023-02-09 16:30 UTC, akurtakov commented on tests/org.eclipse.jface.tests/src/org/eclipse/jface/tests/dialogs/StatusDialogTest.java
> + *     R�diger Herrmann - initial API and implementation
Name broke.

2023-02-09 16:30 UTC, akurtakov commented on tests/org.eclipse.jface.tests/src/org/eclipse/jface/tests/images/DecorationOverlayIconTest.java
> +		assertEquals(icon1, icon2);
This test is testing equals implementation so these should stay calling equals.

2023-02-09 16:30 UTC, akurtakov commented on tests/org.eclipse.jface.tests/src/org/eclipse/jface/tests/images/DecorationOverlayIconTest.java
> +		assertEquals(equalButDifferent1, equalButDifferent2);
same

2023-02-09 20:42 UTC, vrubezhny commented on tests/org.eclipse.jface.tests/src/org/eclipse/jface/tests/dialogs/StatusDialogTest.java
> + *     R�diger Herrmann - initial API and implementation
OK

2023-02-09 20:42 UTC, vrubezhny commented on tests/org.eclipse.jface.tests/src/org/eclipse/jface/tests/images/DecorationOverlayIconTest.java
> +		assertEquals(icon1, icon2);
OK

2023-02-09 20:42 UTC, vrubezhny commented on tests/org.eclipse.jface.tests/src/org/eclipse/jface/tests/images/DecorationOverlayIconTest.java
> +		assertEquals(equalButDifferent1, equalButDifferent2);
OK

2023-02-10 07:38 UTC, akurtakov requested changes

2023-02-10 07:38 UTC, akurtakov commented on tests/org.eclipse.jface.tests/src/org/eclipse/jface/tests/dialogs/StatusDialogTest.java
> + *     Rüdiger Herrmann - initial API and implementation
Broken name

2023-02-10 13:59 UTC, vrubezhny commented on tests/org.eclipse.jface.tests/src/org/eclipse/jface/tests/dialogs/StatusDialogTest.java
> + *     Rüdiger Herrmann - initial API and implementation
Is it?

2023-02-10 14:00 UTC, akurtakov commented on tests/org.eclipse.jface.tests/src/org/eclipse/jface/tests/dialogs/StatusDialogTest.java
> + *     Rüdiger Herrmann - initial API and implementation
yes, preserve it please

2023-02-10 14:00 UTC, akurtakov commented
And rebase on master

2023-02-10 16:03 UTC, vrubezhny commented
Rebased

2023-02-10 17:07 UTC, akurtakov approved these changes

2023-02-10 17:07 UTC, merged