Propagate the exception that make the image creation fail
eclipse-platform/eclipse.platform.ui pull request #634
Opened 2023-03-15 08:08 UTC by laeubi

Currently if image creation fails, only a very generic "Unable to create resource" exception is thrown and the caller has no clue what is actually going on.

This changes the code that the original exception is propagated as the cause.

See https://github.com/eclipse-platform/eclipse.platform.releng/issues/210

2023-03-15 10:44 UTC, laeubi commented
@iloveeclipse it seems not be a problem of the build, because now test also fail with:

```
Caused by: java.lang.IllegalArgumentException: Argument not valid: ImageDataProvider [org.eclipse.jface.resource.ImageDescriptor$$Lambda$286/0x0000000800f668e0@64420e34] returns null ImageData at 100% zoom.
	at org.eclipse.swt.SWT.error(SWT.java:4899)
	at org.eclipse.swt.internal.DPIUtil.validateAndGetImageDataAtZoom(DPIUtil.java:412)
	at org.eclipse.swt.graphics.Image.<init>(Image.java:659)
	at org.eclipse.jface.resource.ImageDescriptor.createResource(ImageDescriptor.java:231)
	... 90 more
```

so it seems something has changed in JFace or SWT?

2023-03-15 10:47 UTC, akurtakov commented
If I'm to guess the new containers built by  https://www.eclipse.org/lists/platform-releng-dev/msg39195.html are broken somehow.

2023-03-15 10:50 UTC, laeubi commented
I now enhanced the error reporting even further lets see if that reveals something...

2023-05-08 12:19 UTC, jukzi requested changes

2023-05-08 12:19 UTC, jukzi commented on bundles/org.eclipse.jface/src/org/eclipse/jface/resource/ImageDescriptor.java
> -		Image result = createImage(false, device);
createImage() is not final so it can not be inlined.

2023-10-02 15:18 UTC, closed without merging