Reduce size of onboarding composite when content is shown
eclipse-platform/eclipse.platform.ui pull request #684
Opened 2023-04-02 08:49 UTC by marcushoepfner

issue #678

The onboarding composite shall leave a space of 50 px to each size. Othewise tabfolder borders are not shown.

2023-04-02 08:50 UTC, marcushoepfner commented
Any better idea than leaving 50px spacing to each side? I unfortunately did not find the actual drawing (and the space) of these border lines.

2023-04-03 05:34 UTC, marcushoepfner commented
I think the test error are the same as mentioned here #665 and not related to this PR.

2023-04-03 05:38 UTC, BeckerWdf requested changes

2023-04-03 05:38 UTC, BeckerWdf commented on bundles/org.eclipse.e4.ui.workbench.renderers.swt/src/org/eclipse/e4/ui/workbench/renderers/swt/StackRenderer.java
> +			int spacing = 50;
```suggestion
			int spacing = 50; //Needed so that tabfolder borders are still shown
```

2023-04-03 05:43 UTC, BeckerWdf commented
I tested it and looks good

2023-04-03 07:40 UTC, BeckerWdf approved these changes

2023-04-03 07:48 UTC, merged