Fix JstPipelineTest
eclipse-platform/eclipse.platform.ui pull request #691
Opened 2023-04-04 06:59 UTC by marcushoepfner

Issue: https://github.com/eclipse-platform/eclipse.platform.ui/issues/665

2023-04-04 07:12 UTC, vogella commented on tests/org.eclipse.ui.tests.navigator/src/org/eclipse/ui/tests/navigator/jst/JstPipelineTest.java
> +		assertEquals("There should be two visible extensions for the pipeline viewer.", 3,
I know this is old, but "two visible extension" vs using 3 sounds something we should adjust.

2023-04-04 07:12 UTC, vogella requested changes
Thanks for working on this Marcus.

2023-04-04 07:41 UTC, marcushoepfner commented on tests/org.eclipse.ui.tests.navigator/src/org/eclipse/ui/tests/navigator/jst/JstPipelineTest.java
> +		assertEquals("There should be two visible extensions for the pipeline viewer.", 3,
Done. Did not see it.

2023-04-04 07:44 UTC, marcushoepfner commented
> Thanks for working on this Marcus.

Sure. Don't really understand the test. But I can see, that the Test is not working on Jenkins (mac). While locally it works on Mac (in Eclipse as PDE test).

Let's wait for the build to finish and check the console.

2023-04-04 08:46 UTC, marcushoepfner commented
> Thanks for working on this Marcus.

Sure. But I got some errors I don't understand. In order to understand the problem I added some system outs.

On Linux or Windows on Jenkins (both are similar), the children of the "Compressed Java" node are like this:
`Starting here ... ==================================================
Compressed Libraries
java.base - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.compiler - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.datatransfer - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.desktop - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.instrument - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.logging - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.management - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.management.rmi - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.naming - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.net.http - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.prefs - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.rmi - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.scripting - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.se - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.security.jgss - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.security.sasl - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.sql - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.sql.rowset - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.transaction.xa - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.xml - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
java.xml.crypto - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.accessibility - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.attach - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.compiler - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.dynalink - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.httpserver - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.incubator.foreign - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.incubator.vector - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.internal.ed - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.internal.jvmstat - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.internal.le - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.internal.opt - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.jartool - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.javadoc - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.jconsole - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.jdi - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.jdwp.agent - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.jfr - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.jshell - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.jsobject - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.management - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.management.agent - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.management.jfr - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.net - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.nio.mapmode - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.sctp - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.security.auth - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.security.jgss - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.unsupported - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.unsupported.desktop - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
jdk.xml.dom - /usr/lib/jvm/temurin-17-jdk-amd64/lib/jrt-fs.jar
src
Done======================`

While on Mac (Jenkins) like this:
`Starting here ... ==================================================
(default package)
a.b.c.d
Compressed Libraries
Done======================`

Locally on my mac machine it looks on Jenkins for Linux/Windows.

Is the JDT/JVM setup wrongly for Mac on Jenkins?

I have no clue how to fix this.
@vogella  could you assist or do you know someone who could help?

2023-04-04 09:22 UTC, vogella commented
I have no idea about Mac in general.

2023-04-04 11:27 UTC, marcushoepfner commented
who set up the jenkins (for mac)?

2023-04-04 11:39 UTC, laeubi commented
> who set up the jenkins (for mac)?

There is no mac Jenkins instance for platform, we have only mac runners on github.
You can see the full setup here:
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.github/workflows/mavenBuild.yml

But mac test sometime require special care if they using `jdt.launching`, not sure if it might be the case here:
- https://github.com/eclipse-pde/eclipse.pde/pull/545

2023-04-04 11:50 UTC, marcushoepfner commented
> > who set up the jenkins (for mac)?
> 
> There is no mac Jenkins instance for platform, we have only mac runners on github. You can see the full setup here: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.github/workflows/mavenBuild.yml
> 
> But mac test sometime require special care if they using `jdt.launching`, not sure if it might be the case here:
> 
>     * [Use p2.inf to pull in depedency to org.eclipse.jdt.launching.macosx eclipse-pde/eclipse.pde#545](https://github.com/eclipse-pde/eclipse.pde/pull/545)

will try p2.inf file

2023-04-04 14:11 UTC, marcushoepfner commented
> > > who set up the jenkins (for mac)?
> > 
> > 
> > There is no mac Jenkins instance for platform, we have only mac runners on github. You can see the full setup here: https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/blob/master/.github/workflows/mavenBuild.yml
> > But mac test sometime require special care if they using `jdt.launching`, not sure if it might be the case here:
> > ```
> > * [Use p2.inf to pull in depedency to org.eclipse.jdt.launching.macosx eclipse-pde/eclipse.pde#545](https://github.com/eclipse-pde/eclipse.pde/pull/545)
> > ```
> 
> will try p2.inf file

Did work! Thanks for the hint @laeubi

2023-04-05 06:27 UTC, marcushoepfner commented
@vogella Seems that I need a re-review from you side. Only then I can merge. Thanks

2023-04-05 07:45 UTC, vogella approved these changes
The test failure in org.eclipse.ui.tests.navigator looks unrelated

2023-04-05 07:54 UTC, merged