Revert reusable ImageFileNameProvider/ImageDataProvider instances of
eclipse-platform/eclipse.platform.ui pull request #701
Opened 2023-04-04 16:36 UTC by Dani-Hub

URLImageDescriptor and FileImageDescriptor

This fixes #679: It restores the Image#equals contract, which depends on non-equal providers per image.

The corresponding tests are modified, too: Now they assert non-sameness of the provider instead of sameness.

To preserve the testability of their underlying providers, the two affected ImageDescriptor classes return them now through their getAdapter methods (And so so similarly by creating fresh instances).

2023-04-04 18:31 UTC, iloveeclipse commented
@Dani-Hub : could you please do following :    

1) Add comments in the image creation code that mentions that we **want** new instances of providers to make sure the code that uses created images can use equals()
2) Optionally (but high wanted) : could you provide a test case that opens plain text editor on few files in the way "Search" it does, and checks that editor tab doesn't loose the icon?

2023-04-05 04:37 UTC, Dani-Hub commented
> @Dani-Hub : could you please do following :
> 
>     1. Add comments in the image creation code that mentions that we **want** new instances of providers to make sure the code that uses created images can use equals()

Sure, will do that (this evening)

>     2. Optionally (but high wanted) : could you provide a test case that opens plain text editor on few files in the way "Search" it does, and checks that editor tab doesn't loose the icon?

I need a bit of guidance here. Can you show me a test project that does something similarly? (This sounds more like an integration test, but maybe I misunderstand.)

2023-04-05 06:07 UTC, iloveeclipse commented
> I need a bit of guidance here. Can you show me a test project that does something similarly?

Will do it later.

But you are right, more easier would be a simple unit test for images created with each of the descriptors - they shouldn't be equal if created with same descriptor.

Unfortunately such unit test was not added initially but we can add it now.

2023-04-05 06:32 UTC, Dani-Hub commented
> > I need a bit of guidance here. Can you show me a test project that does something similarly?
> 
> Will do it later.
> 
> But you are right, more easier would be a simple unit test for images created with each of the descriptors - they shouldn't be equal if created with same descriptor.
> 
> Unfortunately such unit test was not added initially but we can add it now.

Not a problem, I'll add such tests.

2023-04-05 15:41 UTC, Dani-Hub commented
@iloveeclipse I have amended my previous PULL request. Can you please review?

2023-04-05 15:57 UTC, iloveeclipse commented on bundles/org.eclipse.jface/src/org/eclipse/jface/resource/URLImageDescriptor.java
> +	private static class URLImageDataProvider implements ImageDataProvider {
What is the reason to duplicate the method implementation here?
Why can't we do something like this:

```
	private class URLImageDataProvider implements ImageDataProvider {
		@Override
		public ImageData getImageData(int zoom) {
			return URLImageDescriptor.this.getImageData(zoom);
		}
	}
```

or extract the main part of `getImageData(zoom)` to a static method and do something like this:

```
	private static class URLImageDataProvider implements ImageDataProvider {
		private final String url;

		public URLImageDataProvider(String url) {
			this.url = url;
		}
		
		@Override
		public ImageData getImageData(int zoom) {
			return URLImageDescriptor.getImageData(zoom, url);
		}

	}

	@Override
	public ImageData getImageData(int zoom) {
		return getImageData(zoom, url);
	}
	
	static ImageData getImageData(int zoom, String url) {
		URL tempURL = getURL(url);
		if (tempURL != null) {
			if (zoom == 100) {
				return getImageData(tempURL);
			}
			URL xUrl = getxURL(tempURL, zoom);
			if (xUrl != null) {
				ImageData xdata = getImageData(xUrl);
				if (xdata != null) {
					return xdata;
				}
			}
			String xpath = FileImageDescriptor.getxPath(url, zoom);
			if (xpath != null) {
				URL xPathUrl = getURL(xpath);
				if (xPathUrl != null) {
					return getImageData(xPathUrl);
				}
			}
		}
		return null;
	}
```

2023-04-05 16:05 UTC, iloveeclipse requested changes
Two things: 
1) Avoid code duplication (see comment above)
2) Add the `UrlImageDescriptorTest` class to AllImagesTests (not your fault, it wasn't added before)

2023-04-05 16:05 UTC, iloveeclipse commented on tests/org.eclipse.jface.tests/src/org/eclipse/jface/tests/images/UrlImageDescriptorTest.java
> +	/**
Please add this class to `AllImagesTests`

2023-04-05 16:15 UTC, Dani-Hub commented
> Two things:
> 
>     1. Avoid code duplication (see comment above)
> 
>     2. Add the `UrlImageDescriptorTest` class to AllImagesTests (not your fault, it wasn't added before)

All good points - implemented now.

Can you help me understand, why the IT is still failing?

2023-04-05 16:41 UTC, iloveeclipse commented
> Can you help me understand, why the IT is still failing?

Sorry, I've missed that part completely.
The manifest from org.eclipse.e4.ui.tests needs a version update +100 in the last segment.

2023-04-05 16:44 UTC, Dani-Hub commented
> > Can you help me understand, why the IT is still failing?
> 
> Sorry, I've missed that part completely. The manifest from org.eclipse.e4.ui.tests needs a version update +100 in the last segment.

I assume you mean org.eclipse.jface.tests, right? Thanks for the hint.

2023-04-05 16:46 UTC, iloveeclipse commented
> I assume you mean org.eclipse.jface.tests, right? Thanks for the hint.

No, sorry, I see your PR is not based on master head. Please rebase and problem should disappear.

2023-04-05 16:48 UTC, iloveeclipse commented on tests/org.eclipse.jface.tests/META-INF/MANIFEST.MF
> +Bundle-Version: 1.4.100.qualifier
Please undo, that is not needed.

2023-04-05 16:49 UTC, iloveeclipse commented
See above: **This branch is out-of-date with the base branch**

Please fetch from master and rebase your branch on top of master!

2023-04-05 17:10 UTC, Dani-Hub commented
> See above: **This branch is out-of-date with the base branch**
> 
> Please fetch from master and rebase your branch on top of master!

I have done that (I hope correctly9, but the fourth test still fails with 

> Failed to execute goal org.eclipse.tycho.extras:tycho-p2-extras-plugin:4.0.0-SNAPSHOT:compare-version-with-baselines (compare-attached-artifacts-with-release) on project org.eclipse.jface.tests: Only qualifier changed for (org.eclipse.jface.tests/1.4.0.v20230405-1654). Expected to have bigger x.y.z than what is available

Doesn't that mean that I still need to increase the z part (micro) of the version number?

2023-04-05 17:13 UTC, iloveeclipse commented
> Doesn't that mean that I still need to increase the z part (micro) of the version number?

yes. sorry for wrong advice, have checked wrong manifest

2023-04-05 17:17 UTC, Dani-Hub commented
> yes. sorry for wrong advice, have checked wrong manifest

No problem, your guidance is very much appreciated.

2023-04-05 17:35 UTC, Dani-Hub commented
@iloveeclipse I fixed the version constraint mismatch, but now the fourth test still fails because of test failures in other test projects. I'm not so familiar with them to determine the problem, albeit my guess is that these are unrelated to my PULL request.

2023-04-05 17:38 UTC, iloveeclipse commented
continuous-integration/jenkins/pr-head is what to watch for. The rest is currently broken.

2023-04-05 18:09 UTC, iloveeclipse approved these changes
Thanks, LGTM

2023-04-05 18:11 UTC, merged