Adapt ext point description for onboarding image
eclipse-platform/eclipse.platform.ui pull request #721
Opened 2023-04-17 11:12 UTC by marcushoepfner

Size shall be 250x250.

Issue: https://github.com/eclipse-platform/eclipse.platform.ui/issues/702

2023-04-17 11:33 UTC, BeckerWdf requested changes

2023-04-17 11:33 UTC, BeckerWdf commented on bundles/org.eclipse.ui/schema/perspectiveExtensions.exsd
> +Plus a second image for high resolution with a size of 350 x 350 px and a name like [image_name]@2x.[image_type].
```suggestion
Plus a second image for high resolution with a size of 500 x 500 px and a name like [image_name]@2x.[image_type].
```

2023-04-17 11:48 UTC, BeckerWdf approved these changes

2023-04-17 13:07 UTC, merged

2023-04-18 08:25 UTC, iloveeclipse commented
@marcushoepfner : please **do not ignore** "block merge commit" checks!
![image](https://user-images.githubusercontent.com/964108/232718166-fe8f10a9-51b1-43a0-aa39-5e0e6a2303f2.png)

@laeubi : this is what I mean "people learn to ignore errors".

2023-04-18 08:35 UTC, laeubi commented
@iloveeclipse you are **project lead** on platform, you can ask the infrateam to [enable branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule) that forbid merging if certain checks fail. 
So please don't blame the checks for being ignored by people, maybe better people should learn to not merge things blindly ...

2023-04-18 08:38 UTC, iloveeclipse commented
> [enable branch protection rules](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule) that forbid merging if certain checks fail.

Actually I see someone enabled merge commits for platform UI. I've disabled that now. I will also check other repos now, they actually should be all with disabled merge.

2023-04-18 08:41 UTC, iloveeclipse commented
> So please don't blame the checks for being ignored by people, maybe better people should learn to not merge things blindly ...

I will continue to blame the **failing** checks added without anyone committed to work on fixing the fails.
This causes **constant** pain for everyone and people don't understand if the failures are related to their changes or not.

2023-04-18 08:42 UTC, merks commented
Probably merge was enabled to support merging in another repo and then not disabled again afterwards...

2023-04-18 08:44 UTC, laeubi commented
> Actually I see someone enabled merge commits for platform UI. I've disabled that now. 

Requiring a sucessfull check is nothing that can be enabled by the "normal" people, for example currently one can even merge if all check fail.

> This causes constant pain for everyone and people don't understand if the failures are related to their changes or not.

No pain no gain ... I recently heard we have stabilization weeks where people only working on stabilize things?!? So if **everyone** that  feels the pain would help to fix a single test ... but it seems easier to complain and ignore.

2023-04-18 08:45 UTC, BeckerWdf commented
> I will continue to blame the **failing** checks added without anyone committed to work on fixing the fails. This causes **constant** pain for everyone and people don't understand if the failures are related to their changes or not.

Yes this really is an issue.

2023-04-18 08:46 UTC, laeubi commented
> > I will continue to blame the **failing** checks added without anyone committed to work on fixing the fails. This causes **constant** pain for everyone and people don't understand if the failures are related to their changes or not.
> 
> Yes this really is an issue.

The start fixing the issue or be more careful when merging. You ignored a check **that has never failed before** so please don't blame other checks for ignoring ones that work exactly as intended.

2023-04-18 08:55 UTC, merks commented
It would be nice to be a bit nicer.  Yes, failing tests cause us to eventually ignore failing tests, and that is to our own peril.  Yes, when I come and fix one little problem, and I only have time for fixing that one little problem, I will tend to ignore unrelated failing tests. Yes, we should all feel responsible for fixing failing tests, even those that are not our own.   Who is at fault is not really so important.

2023-04-18 08:57 UTC, marcushoepfner commented
> @marcushoepfner : please **do not ignore** "block merge commit" checks! ![image](https://user-images.githubusercontent.com/964108/232718166-fe8f10a9-51b1-43a0-aa39-5e0e6a2303f2.png)
> 
> @laeubi : this is what I mean "people learn to ignore errors".

Sorry for that. Broken window effect I guess. I just threw another stone.
Did it break something in main branch? Do I need to fix something?

2023-04-18 09:06 UTC, laeubi commented
@merks a completely unrelated check (NOT regarding test failures) was ignored, and I assume it the **responsibility of the committer** to check if the test failure is really unrelated and not **ignore any failing check**.

Also please note that **it was explicitly requested** that failing test **should also fail the builds** here (before only the Junit check has failed but not the build):
- https://github.com/eclipse-platform/eclipse.platform.swt/issues/594

beside that we have had in the past enough examples where a regression was only discovered at the ibuilds (or even first at the user tests) because we before has only checked the Linux builds!
Also **there are people** that are working on fixing the test so I find it really unfair and not "friendly" for those that really try to improve things here that they have **not fixed all issue** for us and instead we are "annoyed"...

so sorry for being "not so nice" that now everyone uses some failing tests as an excuse to ignore common development practice and just merge as they find useful.

2023-04-18 09:31 UTC, merks commented
@laeubi  

You are of course correct.  My "it's nice to be nice" comment was not direct only and specifically to you.  Given the pervasiveness and relevance of your contributions to make things work better and better, I think you most definitely are entitled to be treated nicely.   🏅  What goes around, comes around, so its just nicer to be nicer. 👼

2023-04-18 10:16 UTC, iloveeclipse commented
> Broken window effect I guess. I just threw another stone.

Exact what I mean. Once the people are "used" to see errors **in every PR**, they start to ignore them.

> I rewrote history now I think. 

No, you didn't 

> Can this be fixed?

Nothing to fix now. Please just next time avoid merging if **anything** looks suspicious.

2023-04-18 10:22 UTC, laeubi commented
> Once the people are "used" to see errors in every PR, they start to ignore them.

Please don't generalize that, I don't do that and other don't do that as well. And the check in question has not failed on _every_ PR, it has only failed on _this_ PR.

But nice to know, that next time the **freeze check** fails on **every** PR I can assume it can be ignored!

2023-04-18 10:48 UTC, laeubi commented
> Given the pervasiveness and relevance of your contributions to make things work better and better

 there are also others that have done a great job recently to stabilize test:
- https://github.com/eclipse-platform/eclipse.platform/pulls?q=is%3Apr+author%3AHeikoKlare

Also @HannesWell has fixed several things on windows already
- https://github.com/eclipse-pde/eclipse.pde/pulls?q=is%3Apr+author%3AHannesWell

and I think it was you to being very eager and finally fixing the "661 test failures" at PDE ... so claiming no one is "dedicated" is really not true and I think that at least as valuable (if even not more valuable) than new features

> What goes around, comes around, so its just nicer to be nicer.

:+1:  I just take the opportunity here:
- https://github.com/eclipse-platform/eclipse.platform/issues/408

2023-04-18 11:46 UTC, iloveeclipse commented
> Please don't generalize that, 

**I** do not generalize, is is a [well known theory](https://en.wikipedia.org/wiki/Broken_windows_theory). 
 
> But nice to know, that next time the **freeze check** fails on **every** PR I can assume it can be ignored!

This is not funny anymore. I would revert every commit that intentionally ignored freeze check.